#!/usr/bin/env python3
"""Generate HOL checks that the exact basis selection reproduces native runs.

For every captured run with an initial-basis record, the generated theory
states that Tableau_Initial_Basis.native_initial_tableau, applied to the run's
source query, gives exactly the basic and nonbasic index orders that
Engine::processInputQuery chose. The records are untrusted: a wrong record
makes code_simp fail. The theorems say nothing about soundness, which does
not depend on the basis; they check that the HOL selection copies the native
one on these inputs.
"""
import argparse
import hashlib
from pathlib import Path
import sys

import import_marabou_json as proof
import import_marabou_source as source_adapter

ISABELLE = Path(__file__).resolve().parents[1]
FIXTURES = ISABELLE / "tests/fixtures/marabou"
THEORY = "Imported_Marabou_Initial_Bases"
FORMAT = "marabou-initial-basis-v1"
# Scenario runs, then file runs with their own artifacts. File examples that
# reproduce a scenario share its data and are not repeated.
RUNS = ("solver_linear", "solver_relu", "solver_relu_aux", "solver_relu_aux_active",
        "solver_relu_aux_inactive", "solver_relu_split", "solver_relu_intro",
        "solver_relu_sequence", "solver_relu_chain", "solver_relu_sat",
        "file_inequality_relu_unsat", "file_inequality_relu_sat", "file_inequality_linear_sat",
        "file_phase_active_unsat", "file_phase_inactive_unsat", "file_phase_chain_unsat",
        "file_phase_fixed_sat", "file_preprocess_split_unsat", "file_preprocess_eliminate_unsat",
        "file_preprocess_mixed_sat")


def parse_basis(obj, source):
    """Strictly parse a record against its source query's dimensions."""
    proof.fields(obj, ("format", "source_variables", "rows", "basic", "nonbasic"))
    proof.require(obj["format"] == FORMAT, "unsupported initial-basis format")
    n, m = source.n, len(source.equations)
    proof.require(obj["source_variables"] == n and type(obj["source_variables"]) is int,
                  "initial basis does not match the source variables")
    proof.require(obj["rows"] == m and type(obj["rows"]) is int,
                  "initial basis does not match the source rows")
    basic = tuple(proof.index(v, n + m) for v in proof.array(obj["basic"]))
    nonbasic = tuple(proof.index(v, n + m) for v in proof.array(obj["nonbasic"]))
    proof.require(len(basic) == m and len(nonbasic) == n, "initial basis has the wrong size")
    proof.require(sorted(basic + nonbasic) == list(range(n + m)),
                  "initial basis is not a partition of the variables")
    return basic, nonbasic


def load_run(stem, fixtures=FIXTURES):
    source_path = fixtures / (stem + "_source.json")
    basis_path = fixtures / (stem + "_initial_basis.json")
    source = source_adapter.parse_source(proof.load_json(source_path)[0])
    basic, nonbasic = parse_basis(proof.load_json(basis_path)[0], source)
    hashes = tuple(hashlib.sha256(p.read_bytes()).hexdigest() for p in (source_path, basis_path))
    return source, basic, nonbasic, hashes


def render(runs=RUNS, fixtures=FIXTURES):
    parts = [f"""theory {THEORY}
  imports Tableau_Initial_Basis Rational_Linear_Constraints
begin

text \\<open>
  Generated by tools/import_initial_basis.py from the captured source queries
  and initial-basis records in tests/fixtures/marabou. Each lemma states that
  the exact selection of Tableau_Initial_Basis, the checked pivots and the
  index lists reproduce the basic and nonbasic orders that
  Engine::processInputQuery chose in that native run. The records are not
  trusted; soundness of the solver does not depend on them.
\\<close>
"""]
    for stem in runs:
        source, basic, nonbasic, (source_hash, basis_hash) = load_run(stem, fixtures)
        parts.append(f"""
text \\<open>{stem}: {source.n} variables, {len(source.equations)} row{"s" if len(source.equations) != 1 else ""}
  (source SHA-256 {source_hash[:16]}, record SHA-256 {basis_hash[:16]}).\\<close>

definition {stem}_source :: rat_query where
  "{stem}_source =
     {source_adapter.hol_source(source)}"

lemma {stem}_native_initial_basis:
  "map_option (\\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau {source.n} (embed_query {stem}_source)) =
   Some ({proof.hol_list(str(v) for v in basic)}, {proof.hol_list(str(v) for v in nonbasic)})"
  by code_simp
""")
    parts.append("\nend\n")
    return "".join(parts)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed theory differs from a fresh rendering")
    args = parser.parse_args(argv)
    path = ISABELLE / (THEORY + ".thy")
    text = render()
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            print(f"{path.name} is out of date", file=sys.stderr)
            return 1
        return 0
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
