theory Imported_Marabou_File_Phase_Fixed_Sat
  imports "Marabou_Verification.Rational_Assignment"
begin

text \<open>
  Generated by the untrusted assignment adapter. Query numbers denote exact
  rationals decoded from serialized decimal tokens. Assignment values are the
  exact binary values of the native doubles.
  The code_simp proofs below check every linear atom, bound and ReLU exactly;
  the reconstruction itself is not trusted. The C++ solver, extraction and
  JSON decoding are not verified.
  Before-ReLU query SHA-256: 30f132110bbb26c7d61c66450261ef4d8161f9fdebbe58c2e0430567a1e808f0
  ReLU introduction sequence SHA-256: 3a26c5a6ab60c25f91b8d961f6352ebf7fb9bd8e353073ecbb90357bc5e427ac
  Source query SHA-256: 5e7c1d427e080d1acc8401fd160d66b7c2308ddcdc1e7f6e146b46fe53a17af9
  Introduction list SHA-256: dce950c497669dac9675982b0e8872f8f6fbcabd2a8d305c8df23c3d6812c0bf
  Processed query SHA-256: 1cf17328036b8676afc8ace98f09b106642b72afc87894077afdd8cf7261dcd2
  Native assignment SHA-256: aac69dd5e8578130e7efe94e35df9704a3ba8034d3c7a84a17418be316a78211
\<close>

definition imported_source_query :: rat_query where
  "imported_source_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 1), ((-1), 2)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 3)]) 0],
     rat_query_bounds = [RatLower 0 (1 / 2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 1, RatLower 3 0, RatUpper 3 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_source_column_query :: rat_query where
  "imported_source_column_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 1), ((-1), 2)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 3)]) 0],
     rat_query_bounds = [RatLower 0 (1 / 2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 1, RatLower 3 0, RatUpper 3 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma imported_source_term_order:
  "satisfies_query v (embed_query imported_source_column_query) \<longleftrightarrow>
    satisfies_query v (embed_query imported_source_query)"
  by (simp add: imported_source_query_def imported_source_column_query_def
      embed_query_def satisfies_query_def algebra_simps)

definition imported_steps :: "fixed_aux_step list" where
  "imported_steps = [(0, 4), (1, 5)]"

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 1), ((-1), 2), ((-1), 4)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 3), ((-1), 5)]) 0],
     rat_query_bounds = [RatLower 0 (1 / 2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 1, RatLower 3 0, RatUpper 3 0, RatLower 4 0, RatUpper 4 0, RatLower 5 0, RatUpper 5 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_assignment :: rat_assignment where
  "imported_assignment = [(0, (1 / 2)), (1, (1 / 2)), (2, (1 / 2)), (3, 0), (4, 0), (5, 0)]"

lemma imported_steps_match_query:
  "rat_introduce_fixed_aux_sequence imported_source_column_query imported_steps =
    Some imported_query"
  by code_simp

lemma imported_assignment_checked:
  "check_rat_assignment imported_query imported_assignment"
  by code_simp

theorem imported_query_model:
  "satisfies_query (assignment_valuation imported_assignment) (embed_query imported_query)"
  by (rule check_rat_assignment_sound[OF imported_assignment_checked])

theorem imported_query_satisfiable:
  "satisfiable (embed_query imported_query)"
  by (rule check_rat_assignment_satisfiable[OF imported_assignment_checked])

lemma imported_source_assignment_checked:
  "check_rat_assignment imported_source_query imported_assignment"
  by code_simp

theorem imported_source_query_model:
  "satisfies_query (assignment_valuation imported_assignment) (embed_query imported_source_query)"
  by (rule check_rat_assignment_sound[OF imported_source_assignment_checked])

theorem imported_source_query_satisfiable_via_processed:
  "satisfiable (embed_query imported_source_query)"
proof -
  have "satisfiable (embed_query imported_source_column_query)"
    by (rule fixed_aux_sequence_assignment_satisfiable[OF imported_steps_match_query
          imported_assignment_checked])
  then show ?thesis by (simp add: satisfiable_def imported_source_term_order)
qed

definition imported_before_relu_query :: rat_query where
  "imported_before_relu_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 1), ((-1), 2)]) 0],
     rat_query_bounds = [RatLower 0 (1 / 2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 1],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_relu_steps :: "relu_aux_step list" where
  "imported_relu_steps = [ReLU_Aux_Step 0 1 3 (Some (1 / 2))]"

lemma imported_relu_introductions_match_source:
  "rat_introduce_relu_aux_sequence imported_before_relu_query imported_relu_steps =
    Some imported_source_query"
  by code_simp

lemma imported_before_relu_assignment_checked:
  "check_rat_assignment imported_before_relu_query imported_assignment"
  by code_simp

theorem imported_before_relu_query_model:
  "satisfies_query (assignment_valuation imported_assignment)
    (embed_query imported_before_relu_query)"
  by (rule check_rat_assignment_sound[OF imported_before_relu_assignment_checked])

theorem imported_before_relu_query_satisfiable_via_processed:
  "satisfiable (embed_query imported_before_relu_query)"
  using relu_aux_sequence_satisfiable_iff[OF imported_relu_introductions_match_source]
    imported_source_query_satisfiable_via_processed
  by blast

end
