theory Imported_Marabou_Example_Relu_Sat
  imports "Marabou_Verification.Exact_Query_Format" Imported_Marabou_Native_Relu_Sat
begin

text \<open>
  Generated by the untrusted query-file adapter. The theorems below concern
  decode_query of the exact bytes of examples/relu_sat.mqx
  (266 bytes, SHA-256 f87f12009a19f3f716d1dc1e1b16dac6ea384c997638ba8e7096a1ecee7fc770), which the build checks against the file.
  The native solver read this file with an untrusted C++ reader. Isabelle
  proves that the file's decoding has exactly the constraints of the query
  captured from that run, so neither the reader, the solver nor the JSON
  import is trusted for these conclusions.
\<close>

definition query_file :: bytes where
  "query_file = [109, 97, 114, 97, 98, 111, 117, 45, 101, 120, 97, 99, 116, 45, 113, 117, 101, 114, 121, 45, 118, 49, 10, 101,
    113, 32, 49, 32, 120, 48, 32, 45, 49, 32, 120, 52, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 50,
    32, 45, 49, 32, 120, 53, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 49, 32, 49, 32, 120, 51, 32,
    45, 49, 32, 120, 54, 32, 61, 32, 48, 10, 108, 111, 119, 101, 114, 32, 120, 48, 32, 45, 50, 10, 117, 112,
    112, 101, 114, 32, 120, 48, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 49, 32, 48, 10, 117, 112, 112, 101,
    114, 32, 120, 49, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 50, 32, 45, 50, 10, 117, 112, 112, 101, 114,
    32, 120, 50, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 51, 32, 48, 10, 117, 112, 112, 101, 114, 32, 120,
    51, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 52, 32, 49, 47, 50, 10, 117, 112, 112, 101, 114, 32, 120,
    52, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 53, 32, 45, 50, 10, 117, 112, 112, 101, 114, 32, 120, 53,
    32, 45, 49, 47, 52, 10, 108, 111, 119, 101, 114, 32, 120, 54, 32, 48, 10, 117, 112, 112, 101, 114, 32, 120,
    54, 32, 49, 10, 114, 101, 108, 117, 32, 120, 48, 32, 120, 49, 10, 114, 101, 108, 117, 32, 120, 50, 32, 120,
    51, 10]"

external_file "examples/relu_sat.mqx"

ML \<open>
  Exact_Query_Text.check_file \<^theory> @{thm query_file_def} "examples/relu_sat.mqx"
\<close>

lemma query_file_decodes_like_capture:
  "decodes_like query_file Imported_Marabou_Native_Relu_Sat.imported_before_relu_query"
  by code_simp

theorem query_file_decodes:
  "\<exists>Q. decode_query query_file = Some Q"
  by (rule decodes_like_decodes[OF query_file_decodes_like_capture])

theorem query_file_model:
  "decode_query query_file = Some Q \<Longrightarrow>
    satisfies_query (assignment_valuation Imported_Marabou_Native_Relu_Sat.imported_assignment) (embed_query Q)"
  by (rule decodes_like_model[OF query_file_decodes_like_capture Imported_Marabou_Native_Relu_Sat.imported_before_relu_query_model])

theorem query_file_satisfiable:
  "decode_query query_file = Some Q \<Longrightarrow> satisfiable (embed_query Q)"
  using query_file_model unfolding satisfiable_def by blast

end
