theory Imported_Marabou_Relu
  imports "Marabou_Verification.Rational_Proof_Trees"
begin

text \<open>
  Generated by the untrusted Marabou JSON adapter. All numbers below denote
  exact rationals decoded from the serialized decimal tokens. This theorem
  concerns this explicit processed query, not an earlier neural-network input.
  Expected query SHA-256: aef68855a7e61a091865b6ff4c2f559660f482482eb1769b3167378fc878b4e4
  Certificate SHA-256: 655fea1274086ab914f1f3f4ab6c20285d53844ba1af5e0ca42b74f506034ca6
\<close>

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 2), ((-1), 3)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 0, RatLower 1 1, RatUpper 1 2, RatLower 2 0, RatUpper 2 3, RatLower 3 0, RatUpper 3 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Relu_Split 0 1
    (Linear_Unsat [1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1])
    (Linear_Unsat [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])"

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

end
