theory Imported_Marabou_Example_Inequality_Relu_Sat
  imports "Marabou_Verification.Bounded_Inequality_Auxiliary" Imported_Marabou_Prepared_Inequality_Relu_Sat
begin

text \<open>
  Generated by the untrusted query-file adapter. The theorems below concern
  decode_query of the exact bytes of examples/inequality_relu_sat.mqx
  (107 bytes, SHA-256 d8df349d628357cb3f54628dea7288310484f867d7473f3107b4bf7a0f26de85), which the build checks against the file.
  The native solver read a locally prepared equality file. Isabelle checks
  fresh signed slacks and exact witnesses for their finite opposite bounds,
  then matches the result to the independently captured native query.
  These theorems concern the original bytes above; the Python preparation,
  C++ reader, solver and JSON import are untrusted.
\<close>

definition query_file :: bytes where
  "query_file = [109, 97, 114, 97, 98, 111, 117, 45, 101, 120, 97, 99, 116, 45, 113, 117, 101, 114, 121, 45, 118, 49, 10, 108,
    101, 32, 49, 32, 120, 48, 32, 60, 61, 32, 49, 10, 103, 101, 32, 49, 32, 120, 49, 32, 62, 61, 32, 49,
    47, 50, 10, 108, 111, 119, 101, 114, 32, 120, 48, 32, 45, 50, 10, 117, 112, 112, 101, 114, 32, 120, 48, 32,
    50, 10, 108, 111, 119, 101, 114, 32, 120, 49, 32, 48, 10, 117, 112, 112, 101, 114, 32, 120, 49, 32, 50, 10,
    114, 101, 108, 117, 32, 120, 48, 32, 120, 49, 10]"

external_file "examples/inequality_relu_sat.mqx"

ML \<open>
  Exact_Query_Text.check_file \<^theory> @{thm query_file_def} "examples/inequality_relu_sat.mqx"
\<close>

definition inequality_steps :: "bounded_inequality_step list" where
  "inequality_steps = [Bounded_Inequality_Step 0 2 3 [1, 0, 0, 1, 0, 0, 0, 0], Bounded_Inequality_Step 1 3 (-3 / 2) [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0]]"

lemma query_file_decodes_like_capture:
  "bounded_decodes_like query_file inequality_steps Imported_Marabou_Prepared_Inequality_Relu_Sat.imported_before_relu_query"
  by code_simp

theorem query_file_decodes:
  "\<exists>Q. decode_query query_file = Some Q"
  by (rule bounded_decodes_like_decodes[OF query_file_decodes_like_capture])

theorem query_file_model:
  "decode_query query_file = Some Q \<Longrightarrow>
    satisfies_query (assignment_valuation Imported_Marabou_Prepared_Inequality_Relu_Sat.imported_assignment) (embed_query Q)"
  by (rule bounded_decodes_like_model[OF query_file_decodes_like_capture Imported_Marabou_Prepared_Inequality_Relu_Sat.imported_before_relu_query_model])

theorem query_file_satisfiable:
  "decode_query query_file = Some Q \<Longrightarrow> satisfiable (embed_query Q)"
  using query_file_model unfolding satisfiable_def by blast

end
