theory Imported_Marabou_Solver_Relu_Aux_Inactive
  imports "Marabou_Verification.Rational_Proof_Trees"
begin

text \<open>
  Generated by the untrusted Marabou JSON adapter. All numbers below denote
  exact rationals decoded from the serialized decimal tokens. This theorem
  concerns this explicit processed query, not an earlier neural-network input.
  Expected query SHA-256: 60aa1199ec5166bfd52e8654f3c530ff921e8ca8bbd39662c21ba45403d820a4
  Certificate SHA-256: bf74145e60ad1ec6ab1037986ec5ea0a30508cdfa939d0cd63a97b676075667d
\<close>

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 3), ((-1), 5)]) 0, RatEq (RatExpr 0 [(1, 2), ((-1), 4), ((-1), 6)]) 0, RatEq (RatExpr 0 [((-1), 0), ((-1), 1), (1, 2), ((-1), 7)]) 0],
     rat_query_bounds = [RatLower 0 0, RatUpper 0 2, RatLower 1 (-2), RatUpper 1 2, RatLower 2 0, RatUpper 2 2, RatLower 3 (1 / 4), RatUpper 3 2, RatLower 4 (1 / 4), RatUpper 4 2, RatLower 5 0, RatUpper 5 0, RatLower 6 0, RatUpper 6 0, RatLower 7 0, RatUpper 7 0],
     rat_relu_atoms = [ReLU 1 2]\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Linear_Bound (RatLower 0 (1 / 4)) [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0]
    (Relu_Aux_Lower_Output_Upper 1 2 0 (1 / 4) 0 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
      [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
      (Linear_Unsat [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]))"

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

end
