theory Imported_Marabou_Prepared_Inequality_Relu_Sat
  imports "Marabou_Verification.Rational_Assignment"
begin

text \<open>
  Generated by the untrusted assignment adapter. Query numbers denote exact
  rationals decoded from serialized decimal tokens. Assignment values are the
  exact binary values of the native doubles.
  The code_simp proofs below check every linear atom, bound and ReLU exactly;
  the reconstruction itself is not trusted. The C++ solver, extraction and
  JSON decoding are not verified.
  Before-ReLU query SHA-256: 7e84796fd728a1da63be91b1de20de963ae8679ae895dc50358e8ed54477254f
  ReLU introduction sequence SHA-256: 5b031167fb157d4ded8bab447da1178a8e437ad4aefb8611cd6923590fa962e2
  Source query SHA-256: 4a70a87b20faa0209b0479e8d10d67fe8efb138efadc0202f6ba42bfd858f7b2
  Introduction list SHA-256: 8b0d136f369b128f79fac0286d25e9fd05e1bbe9ac560c7df1b44b454d53f9aa
  Processed query SHA-256: b3328ef71230b3747296073c6c94b9793228e87ce74213285fd8b534c27668ec
  Native assignment SHA-256: 012ebb198d32b055d1889ad722f9be213c9e6975865d1efb6997cd6e65e0b385
\<close>

definition imported_source_query :: rat_query where
  "imported_source_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), (1, 2)]) 1, RatEq (RatExpr 0 [(1, 1), (1, 3)]) (1 / 2), RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 4)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 3, RatLower 3 (-3 / 2), RatUpper 3 0, RatLower 4 0, RatUpper 4 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_source_column_query :: rat_query where
  "imported_source_column_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), (1, 2)]) 1, RatEq (RatExpr 0 [(1, 1), (1, 3)]) (1 / 2), RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 4)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 3, RatLower 3 (-3 / 2), RatUpper 3 0, RatLower 4 0, RatUpper 4 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma imported_source_term_order:
  "satisfies_query v (embed_query imported_source_column_query) \<longleftrightarrow>
    satisfies_query v (embed_query imported_source_query)"
  by (simp add: imported_source_query_def imported_source_column_query_def
      embed_query_def satisfies_query_def algebra_simps)

definition imported_steps :: "fixed_aux_step list" where
  "imported_steps = [(0, 5), (1, 6), (2, 7)]"

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), (1, 2), ((-1), 5)]) 0, RatEq (RatExpr 0 [(1, 1), (1, 3), ((-1), 6)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 4), ((-1), 7)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 3, RatLower 3 (-3 / 2), RatUpper 3 0, RatLower 4 0, RatUpper 4 2, RatLower 5 1, RatUpper 5 1, RatLower 6 (1 / 2), RatUpper 6 (1 / 2), RatLower 7 0, RatUpper 7 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_assignment :: rat_assignment where
  "imported_assignment = [(0, (1 / 2)), (1, (1 / 2)), (2, (1 / 2)), (3, 0), (4, 0), (5, 1), (6, (1 / 2)), (7, 0)]"

lemma imported_steps_match_query:
  "rat_introduce_fixed_aux_sequence imported_source_column_query imported_steps =
    Some imported_query"
  by code_simp

lemma imported_assignment_checked:
  "check_rat_assignment imported_query imported_assignment"
  by code_simp

theorem imported_query_model:
  "satisfies_query (assignment_valuation imported_assignment) (embed_query imported_query)"
  by (rule check_rat_assignment_sound[OF imported_assignment_checked])

theorem imported_query_satisfiable:
  "satisfiable (embed_query imported_query)"
  by (rule check_rat_assignment_satisfiable[OF imported_assignment_checked])

lemma imported_source_assignment_checked:
  "check_rat_assignment imported_source_query imported_assignment"
  by code_simp

theorem imported_source_query_model:
  "satisfies_query (assignment_valuation imported_assignment) (embed_query imported_source_query)"
  by (rule check_rat_assignment_sound[OF imported_source_assignment_checked])

theorem imported_source_query_satisfiable_via_processed:
  "satisfiable (embed_query imported_source_query)"
proof -
  have "satisfiable (embed_query imported_source_column_query)"
    by (rule fixed_aux_sequence_assignment_satisfiable[OF imported_steps_match_query
          imported_assignment_checked])
  then show ?thesis by (simp add: satisfiable_def imported_source_term_order)
qed

definition imported_before_relu_query :: rat_query where
  "imported_before_relu_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), (1, 2)]) 1, RatEq (RatExpr 0 [(1, 1), (1, 3)]) (1 / 2)],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 3, RatLower 3 (-3 / 2), RatUpper 3 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_relu_steps :: "relu_aux_step list" where
  "imported_relu_steps = [ReLU_Aux_Step 0 1 4 (Some (-2))]"

lemma imported_relu_introductions_match_source:
  "rat_introduce_relu_aux_sequence imported_before_relu_query imported_relu_steps =
    Some imported_source_query"
  by code_simp

lemma imported_before_relu_assignment_checked:
  "check_rat_assignment imported_before_relu_query imported_assignment"
  by code_simp

theorem imported_before_relu_query_model:
  "satisfies_query (assignment_valuation imported_assignment)
    (embed_query imported_before_relu_query)"
  by (rule check_rat_assignment_sound[OF imported_before_relu_assignment_checked])

theorem imported_before_relu_query_satisfiable_via_processed:
  "satisfiable (embed_query imported_before_relu_query)"
  using relu_aux_sequence_satisfiable_iff[OF imported_relu_introductions_match_source]
    imported_source_query_satisfiable_via_processed
  by blast

end
