theory Imported_Marabou_File_Phase_Inactive_Unsat
  imports "Marabou_Verification.Tableau_Auxiliary_Sequence"
    "Marabou_Verification.ReLU_Auxiliary_Sequence"
begin

text \<open>
  Generated by the untrusted source-query adapter from four captured artifacts.
  Numbers denote exact rationals decoded from serialized decimal tokens.
  The source was captured before initialization; introductions are harness
  proposals recovered from added columns, not a native transformation log.
  The proofs below check reordering, introductions, the independent processed
  query, and the recursive proof. Neither the JSON decoder nor C++ is verified.
  Source query SHA-256: 23ca39f7bfab1bf314dd7fd854e0d9a768876ae2ea52f21cb488b27b1b6891e1
  Introduction list SHA-256: dce950c497669dac9675982b0e8872f8f6fbcabd2a8d305c8df23c3d6812c0bf
  Processed query SHA-256: 4b65d54995f5e9561d0816e241b10b29c825a9add7bd1b679ff36955a5086392
  Certificate SHA-256: 9a90823b79a5dd446542265cff80b669def34c97629656e11c603d80b7d0d9b4
\<close>

definition imported_source_query :: rat_query where
  "imported_source_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 1), ((-1), 2)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 3)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 (-1 / 2), RatLower 1 0, RatUpper 1 2, RatLower 2 (1 / 4), RatUpper 2 2, RatLower 3 0, RatUpper 3 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_source_column_query :: rat_query where
  "imported_source_column_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 1), ((-1), 2)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 3)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 (-1 / 2), RatLower 1 0, RatUpper 1 2, RatLower 2 (1 / 4), RatUpper 2 2, RatLower 3 0, RatUpper 3 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma imported_source_term_order:
  "satisfies_query v (embed_query imported_source_column_query) \<longleftrightarrow>
    satisfies_query v (embed_query imported_source_query)"
  by (simp add: imported_source_query_def imported_source_column_query_def
      embed_query_def satisfies_query_def algebra_simps)

definition imported_steps :: "fixed_aux_step list" where
  "imported_steps = [(0, 4), (1, 5)]"

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 1), ((-1), 2), ((-1), 4)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 3), ((-1), 5)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 (-1 / 2), RatLower 1 0, RatUpper 1 2, RatLower 2 (1 / 4), RatUpper 2 2, RatLower 3 0, RatUpper 3 2, RatLower 4 0, RatUpper 4 0, RatLower 5 0, RatUpper 5 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Relu_Fix_Inactive 0 1 (RatUpper 0 (-1 / 2)) [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    (Linear_Unsat [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0])"

lemma imported_steps_match_query:
  "rat_introduce_fixed_aux_sequence imported_source_column_query imported_steps =
    Some imported_query"
  by code_simp

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

lemma imported_source_certificate_checked:
  "check_after_fixed_aux_sequence imported_source_column_query
    imported_steps imported_certificate"
  by (simp add: check_after_fixed_aux_sequence_def imported_steps_match_query
      imported_certificate_checked)

theorem imported_source_equisatisfiable:
  "satisfiable (embed_query imported_query) \<longleftrightarrow>
    satisfiable (embed_query imported_source_query)"
  using fixed_aux_sequence_satisfiable_iff[OF imported_steps_match_query]
  by (simp add: satisfiable_def imported_source_term_order)

theorem imported_source_query_unsatisfiable:
  "unsatisfiable (embed_query imported_source_query)"
proof -
  have "unsatisfiable (embed_query imported_source_column_query)"
    by (rule check_after_fixed_aux_sequence_sound[OF imported_source_certificate_checked])
  then show ?thesis
    by (simp add: unsatisfiable_def satisfiable_def imported_source_term_order)
qed

text \<open>
  Additional native ReLU introduction sequence and independent before-query.
  Each step checks the current query. The whole final result must equal
  imported_source_query, captured independently after the native calls.
  Before-ReLU query SHA-256: 7e40eedf37e1e35f42fa1407c92b7ed247eba1f4909b262f8d5e43ea91f4cbf5
  ReLU introduction sequence SHA-256: 8cb856a22f6cfce9c77756067490633de347b7aa238252b4c18fcc3a273c2863
\<close>

definition imported_before_relu_query :: rat_query where
  "imported_before_relu_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 1), ((-1), 2)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 (-1 / 2), RatLower 1 0, RatUpper 1 2, RatLower 2 (1 / 4), RatUpper 2 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_relu_steps :: "relu_aux_step list" where
  "imported_relu_steps = [ReLU_Aux_Step 0 1 3 (Some (-2))]"

lemma imported_relu_introductions_match_source:
  "rat_introduce_relu_aux_sequence imported_before_relu_query imported_relu_steps =
    Some imported_source_query"
  by code_simp

theorem imported_relu_introductions_equisatisfiable:
  "satisfiable (embed_query imported_source_query) \<longleftrightarrow>
    satisfiable (embed_query imported_before_relu_query)"
  by (rule relu_aux_sequence_satisfiable_iff[OF imported_relu_introductions_match_source])

theorem imported_before_relu_processed_equisatisfiable:
  "satisfiable (embed_query imported_query) \<longleftrightarrow>
    satisfiable (embed_query imported_before_relu_query)"
  using imported_source_equisatisfiable imported_relu_introductions_equisatisfiable by blast

lemma imported_before_relu_certificate_checked:
  "check_after_relu_aux_sequence imported_before_relu_query imported_relu_steps
    imported_steps imported_certificate"
  by code_simp

theorem imported_before_relu_query_unsatisfiable:
  "unsatisfiable (embed_query imported_before_relu_query)"
  by (rule check_after_relu_aux_sequence_sound[OF imported_before_relu_certificate_checked])

end
