theory Imported_Marabou_Initial_Bases
  imports Tableau_Initial_Basis Rational_Linear_Constraints
begin

text \<open>
  Generated by tools/import_initial_basis.py from the captured source queries
  and initial-basis records in tests/fixtures/marabou. Each lemma states that
  the exact selection of Tableau_Initial_Basis, the checked pivots and the
  index lists reproduce the basic and nonbasic orders that
  Engine::processInputQuery chose in that native run. The records are not
  trusted; soundness of the solver does not depend on them.
\<close>

text \<open>solver_linear: 2 variables, 1 row
  (source SHA-256 e9a060673c6a2551, record SHA-256 08cd45d0989b0d75).\<close>

definition solver_linear_source :: rat_query where
  "solver_linear_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 1)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 (1 / 4), RatLower 1 (1 / 2), RatUpper 1 2],
     rat_relu_atoms = []\<rparr>"

lemma solver_linear_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 2 (embed_query solver_linear_source)) =
   Some ([1], [0, 2])"
  by code_simp

text \<open>solver_relu: 5 variables, 3 rows
  (source SHA-256 d7117b9a0275fcb3, record SHA-256 5bc1185017aec9f4).\<close>

definition solver_relu_source :: rat_query where
  "solver_relu_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 2)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 4)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 3)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 (-1), RatUpper 2 (-1 / 2), RatLower 3 (1 / 4), RatUpper 3 2, RatLower 4 0, RatUpper 4 1],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma solver_relu_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 5 (embed_query solver_relu_source)) =
   Some ([2, 4, 3], [0, 1, 5, 6, 7])"
  by code_simp

text \<open>solver_relu_aux: 5 variables, 3 rows
  (source SHA-256 46400a38cdb9554e, record SHA-256 112cab42e8d61bfe).\<close>

definition solver_relu_aux_source :: rat_query where
  "solver_relu_aux_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 2)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 3)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 4)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 (-2), RatUpper 2 (-1 / 2), RatLower 3 (1 / 4), RatUpper 3 2, RatLower 4 0, RatUpper 4 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma solver_relu_aux_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 5 (embed_query solver_relu_aux_source)) =
   Some ([2, 3, 4], [0, 1, 5, 6, 7])"
  by code_simp

text \<open>solver_relu_aux_active: 5 variables, 3 rows
  (source SHA-256 0c04cea768c49433, record SHA-256 bf3a7d389d63c29b).\<close>

definition solver_relu_aux_active_source :: rat_query where
  "solver_relu_aux_active_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 2)]) 0, RatEq (RatExpr 0 [(1, 4), ((-1), 3)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 4)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 (1 / 2), RatUpper 2 2, RatLower 3 (1 / 4), RatUpper 3 2, RatLower 4 0, RatUpper 4 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma solver_relu_aux_active_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 5 (embed_query solver_relu_aux_active_source)) =
   Some ([2, 3, 1], [0, 4, 5, 6, 7])"
  by code_simp

text \<open>solver_relu_aux_inactive: 5 variables, 3 rows
  (source SHA-256 2e758d4512ddaa88, record SHA-256 de6972ce7eb33fe6).\<close>

definition solver_relu_aux_inactive_source :: rat_query where
  "solver_relu_aux_inactive_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 3)]) 0, RatEq (RatExpr 0 [(1, 2), ((-1), 4)]) 0, RatEq (RatExpr 0 [(1, 2), ((-1), 1), ((-1), 0)]) 0],
     rat_query_bounds = [RatLower 0 0, RatUpper 0 2, RatLower 1 (-2), RatUpper 1 2, RatLower 2 0, RatUpper 2 2, RatLower 3 (1 / 4), RatUpper 3 2, RatLower 4 (1 / 4), RatUpper 4 2],
     rat_relu_atoms = [ReLU 1 2]\<rparr>"

lemma solver_relu_aux_inactive_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 5 (embed_query solver_relu_aux_inactive_source)) =
   Some ([3, 4, 1], [0, 2, 5, 6, 7])"
  by code_simp

text \<open>solver_relu_split: 9 variables, 5 rows
  (source SHA-256 bb189d900b7453b7, record SHA-256 59133120c9a82c7c).\<close>

definition solver_relu_split_source :: rat_query where
  "solver_relu_split_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 1), ((-1), 3), ((-1), 5)]) (1 / 4), RatEq (RatExpr 0 [(1, 1), (1, 3), ((-1), 6)]) (1 / 4), RatEq (RatExpr 0 [(1, 2), ((-1), 4), ((-1), 7)]) (1 / 4), RatEq (RatExpr 0 [(1, 2), (1, 4), ((-1), 8)]) (1 / 4), RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 2)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 1, RatLower 1 0, RatUpper 1 1, RatLower 2 0, RatUpper 2 1, RatLower 3 (-1), RatUpper 3 1, RatLower 4 (-1), RatUpper 4 1, RatLower 5 0, RatUpper 5 2, RatLower 6 0, RatUpper 6 2, RatLower 7 0, RatUpper 7 2, RatLower 8 0, RatUpper 8 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma solver_relu_split_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 9 (embed_query solver_relu_split_source)) =
   Some ([0, 6, 5, 8, 7], [1, 2, 3, 4, 9, 10, 11, 12, 13])"
  by code_simp

text \<open>solver_relu_intro: 5 variables, 3 rows
  (source SHA-256 46400a38cdb9554e, record SHA-256 112cab42e8d61bfe).\<close>

definition solver_relu_intro_source :: rat_query where
  "solver_relu_intro_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 2)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 3)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 4)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 (-2), RatUpper 2 (-1 / 2), RatLower 3 (1 / 4), RatUpper 3 2, RatLower 4 0, RatUpper 4 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma solver_relu_intro_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 5 (embed_query solver_relu_intro_source)) =
   Some ([2, 3, 4], [0, 1, 5, 6, 7])"
  by code_simp

text \<open>solver_relu_sequence: 8 variables, 5 rows
  (source SHA-256 655afb36d515dcb6, record SHA-256 37a632f8b3207a97).\<close>

definition solver_relu_sequence_source :: rat_query where
  "solver_relu_sequence_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 4)]) 0, RatEq (RatExpr 0 [(1, 2), ((-1), 4)]) 0, RatEq (RatExpr 0 [(1, 1), (1, 3), ((-1), 5)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 6)]) 0, RatEq (RatExpr 0 [(1, 3), ((-1), 2), ((-1), 7)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 (-2), RatUpper 2 2, RatLower 3 0, RatUpper 3 2, RatLower 4 (-2), RatUpper 4 (-1 / 2), RatLower 5 (1 / 4), RatUpper 5 2, RatLower 6 0, RatUpper 6 2, RatLower 7 0, RatUpper 7 2],
     rat_relu_atoms = [ReLU 0 1, ReLU 2 3]\<rparr>"

lemma solver_relu_sequence_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 8 (embed_query solver_relu_sequence_source)) =
   Some ([4, 2, 6, 5, 7], [0, 1, 3, 8, 9, 10, 11, 12])"
  by code_simp

text \<open>solver_relu_chain: 8 variables, 5 rows
  (source SHA-256 599fb10eb505fe7e, record SHA-256 37a632f8b3207a97).\<close>

definition solver_relu_chain_source :: rat_query where
  "solver_relu_chain_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 4)]) 0, RatEq (RatExpr 0 [(1, 2), ((-1), 1)]) (-1 / 4), RatEq (RatExpr 0 [(1, 3), ((-1), 5)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 6)]) 0, RatEq (RatExpr 0 [(1, 3), ((-1), 2), ((-1), 7)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 (-2), RatUpper 2 2, RatLower 3 0, RatUpper 3 2, RatLower 4 (-2), RatUpper 4 (-1 / 2), RatLower 5 (1 / 4), RatUpper 5 2, RatLower 6 0, RatUpper 6 2, RatLower 7 0, RatUpper 7 2],
     rat_relu_atoms = [ReLU 0 1, ReLU 2 3]\<rparr>"

lemma solver_relu_chain_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 8 (embed_query solver_relu_chain_source)) =
   Some ([4, 2, 6, 5, 7], [0, 1, 3, 8, 9, 10, 11, 12])"
  by code_simp

text \<open>solver_relu_sat: 9 variables, 5 rows
  (source SHA-256 b323a2bd2dd3a8b4, record SHA-256 00fa57a5214d48db).\<close>

definition solver_relu_sat_source :: rat_query where
  "solver_relu_sat_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 4)]) 0, RatEq (RatExpr 0 [(1, 2), ((-1), 5)]) 0, RatEq (RatExpr 0 [(1, 1), (1, 3), ((-1), 6)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 7)]) 0, RatEq (RatExpr 0 [(1, 3), ((-1), 2), ((-1), 8)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 (-2), RatUpper 2 2, RatLower 3 0, RatUpper 3 2, RatLower 4 (1 / 2), RatUpper 4 2, RatLower 5 (-2), RatUpper 5 (-1 / 4), RatLower 6 0, RatUpper 6 1, RatLower 7 0, RatUpper 7 2, RatLower 8 0, RatUpper 8 2],
     rat_relu_atoms = [ReLU 0 1, ReLU 2 3]\<rparr>"

lemma solver_relu_sat_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 9 (embed_query solver_relu_sat_source)) =
   Some ([4, 7, 5, 6, 8], [0, 1, 2, 3, 9, 10, 11, 12, 13])"
  by code_simp

text \<open>file_inequality_relu_unsat: 5 variables, 3 rows
  (source SHA-256 225baf6e3f290fd1, record SHA-256 112cab42e8d61bfe).\<close>

definition file_inequality_relu_unsat_source :: rat_query where
  "file_inequality_relu_unsat_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), (1, 2)]) (-1), RatEq (RatExpr 0 [(1, 1), (1, 3)]) 1, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 4)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 1, RatLower 3 (-1), RatUpper 3 0, RatLower 4 0, RatUpper 4 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma file_inequality_relu_unsat_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 5 (embed_query file_inequality_relu_unsat_source)) =
   Some ([2, 3, 4], [0, 1, 5, 6, 7])"
  by code_simp

text \<open>file_inequality_relu_sat: 5 variables, 3 rows
  (source SHA-256 4a70a87b20faa020, record SHA-256 112cab42e8d61bfe).\<close>

definition file_inequality_relu_sat_source :: rat_query where
  "file_inequality_relu_sat_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), (1, 2)]) 1, RatEq (RatExpr 0 [(1, 1), (1, 3)]) (1 / 2), RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 4)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 3, RatLower 3 (-3 / 2), RatUpper 3 0, RatLower 4 0, RatUpper 4 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma file_inequality_relu_sat_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 5 (embed_query file_inequality_relu_sat_source)) =
   Some ([2, 3, 4], [0, 1, 5, 6, 7])"
  by code_simp

text \<open>file_inequality_linear_sat: 3 variables, 1 row
  (source SHA-256 4a062038263be808, record SHA-256 63c5c91bb0a50f47).\<close>

definition file_inequality_linear_sat_source :: rat_query where
  "file_inequality_linear_sat_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 1), (1, 2)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 1, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 4],
     rat_relu_atoms = []\<rparr>"

lemma file_inequality_linear_sat_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 3 (embed_query file_inequality_linear_sat_source)) =
   Some ([1], [0, 2, 3])"
  by code_simp

text \<open>file_phase_active_unsat: 4 variables, 2 rows
  (source SHA-256 068bb13ba149689d, record SHA-256 645da032f11b9bea).\<close>

definition file_phase_active_unsat_source :: rat_query where
  "file_phase_active_unsat_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 2)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 3)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 1, RatLower 1 (3 / 2), RatUpper 1 2, RatLower 2 (-1), RatUpper 2 1, RatLower 3 0, RatUpper 3 1],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma file_phase_active_unsat_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 4 (embed_query file_phase_active_unsat_source)) =
   Some ([2, 3], [0, 1, 4, 5])"
  by code_simp

text \<open>file_phase_inactive_unsat: 4 variables, 2 rows
  (source SHA-256 23ca39f7bfab1bf3, record SHA-256 315f7d66b9fd7b29).\<close>

definition file_phase_inactive_unsat_source :: rat_query where
  "file_phase_inactive_unsat_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 1), ((-1), 2)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 3)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 (-1 / 2), RatLower 1 0, RatUpper 1 2, RatLower 2 (1 / 4), RatUpper 2 2, RatLower 3 0, RatUpper 3 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma file_phase_inactive_unsat_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 4 (embed_query file_phase_inactive_unsat_source)) =
   Some ([2, 0], [1, 3, 4, 5])"
  by code_simp

text \<open>file_phase_chain_unsat: 7 variables, 4 rows
  (source SHA-256 8787822e534f4247, record SHA-256 cc11fe9cd074a3a9).\<close>

definition file_phase_chain_unsat_source :: rat_query where
  "file_phase_chain_unsat_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 2), ((-1), 1)]) (-1 / 4), RatEq (RatExpr 0 [(1, 3), ((-1), 4)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 5)]) 0, RatEq (RatExpr 0 [(1, 3), ((-1), 2), ((-1), 6)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 (-1 / 2), RatLower 1 0, RatUpper 1 2, RatLower 2 (-2), RatUpper 2 2, RatLower 3 0, RatUpper 3 2, RatLower 4 (1 / 4), RatUpper 4 2, RatLower 5 0, RatUpper 5 2, RatLower 6 0, RatUpper 6 2],
     rat_relu_atoms = [ReLU 0 1, ReLU 2 3]\<rparr>"

lemma file_phase_chain_unsat_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 7 (embed_query file_phase_chain_unsat_source)) =
   Some ([2, 4, 6, 0], [1, 3, 5, 7, 8, 9, 10])"
  by code_simp

text \<open>file_phase_fixed_sat: 4 variables, 2 rows
  (source SHA-256 5e7c1d427e080d1a, record SHA-256 315f7d66b9fd7b29).\<close>

definition file_phase_fixed_sat_source :: rat_query where
  "file_phase_fixed_sat_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 1), ((-1), 2)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 3)]) 0],
     rat_query_bounds = [RatLower 0 (1 / 2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 1, RatLower 3 0, RatUpper 3 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma file_phase_fixed_sat_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 4 (embed_query file_phase_fixed_sat_source)) =
   Some ([2, 0], [1, 3, 4, 5])"
  by code_simp

text \<open>file_preprocess_split_unsat: 10 variables, 6 rows
  (source SHA-256 d461e697e82e21fd, record SHA-256 20011b132d9ca550).\<close>

definition file_preprocess_split_unsat_source :: rat_query where
  "file_preprocess_split_unsat_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 1), ((-1), 3), ((-1), 5)]) (1 / 4), RatEq (RatExpr 0 [(1, 1), (1, 3), ((-1), 6)]) (1 / 4), RatEq (RatExpr 0 [(1, 2), ((-1), 4), ((-1), 7)]) (1 / 4), RatEq (RatExpr 0 [(1, 2), (1, 4), ((-1), 8)]) (1 / 4), RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 2)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 9)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 1, RatLower 1 0, RatUpper 1 1, RatLower 2 0, RatUpper 2 1, RatLower 3 (-3 / 4), RatUpper 3 (3 / 4), RatLower 4 (-3 / 4), RatUpper 4 (3 / 4), RatLower 5 0, RatUpper 5 (3 / 2), RatLower 6 0, RatUpper 6 (3 / 2), RatLower 7 0, RatUpper 7 (3 / 2), RatLower 8 0, RatUpper 8 (3 / 2), RatLower 9 0, RatUpper 9 1],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma file_preprocess_split_unsat_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 10 (embed_query file_preprocess_split_unsat_source)) =
   Some ([0, 9, 5, 6, 7, 8], [1, 2, 3, 4, 10, 11, 12, 13, 14, 15])"
  by code_simp

text \<open>file_preprocess_eliminate_unsat: 10 variables, 6 rows
  (source SHA-256 411232ac709e840e, record SHA-256 cff6c8e940cd0602).\<close>

definition file_preprocess_eliminate_unsat_source :: rat_query where
  "file_preprocess_eliminate_unsat_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 2), ((-1), 4)]) (1 / 4), RatEq (RatExpr 0 [(1, 0), (1, 2), ((-1), 5)]) (1 / 4), RatEq (RatExpr 0 [(1, 1), ((-1), 3), ((-1), 6)]) (1 / 4), RatEq (RatExpr 0 [(1, 1), (1, 3), ((-1), 7)]) (1 / 4), RatEq (RatExpr 0 [(1, 0), ((-1), 1), ((-1), 8)]) 0, RatEq (RatExpr 0 [(1, 0), ((-1), 8), ((-1), 9)]) 0],
     rat_query_bounds = [RatLower 0 0, RatUpper 0 1, RatLower 1 0, RatUpper 1 1, RatLower 2 (-3 / 4), RatUpper 2 (3 / 4), RatLower 3 (-3 / 4), RatUpper 3 (3 / 4), RatLower 4 0, RatUpper 4 (3 / 2), RatLower 5 0, RatUpper 5 (3 / 2), RatLower 6 0, RatUpper 6 (3 / 2), RatLower 7 0, RatUpper 7 (3 / 2), RatLower 8 (-1), RatUpper 8 1, RatLower 9 0, RatUpper 9 1],
     rat_relu_atoms = [ReLU 8 0]\<rparr>"

lemma file_preprocess_eliminate_unsat_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 10 (embed_query file_preprocess_eliminate_unsat_source)) =
   Some ([8, 9, 4, 5, 6, 7], [0, 1, 2, 3, 10, 11, 12, 13, 14, 15])"
  by code_simp

text \<open>file_preprocess_mixed_sat: 4 variables, 3 rows
  (source SHA-256 4ead9a8a1a5992e5, record SHA-256 fa9c6460bbbc1df7).\<close>

definition file_preprocess_mixed_sat_source :: rat_query where
  "file_preprocess_mixed_sat_source =
     \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), (1, 2)]) (5 / 4), RatEq (RatExpr 0 [(1, 1), (1, 3)]) (1 / 2), RatEq (RatExpr 0 [(1, 0), ((-1), 1)]) 0],
     rat_query_bounds = [RatLower 0 (1 / 2), RatUpper 0 (5 / 4), RatLower 1 (1 / 2), RatUpper 1 (5 / 4), RatLower 2 0, RatUpper 2 (3 / 4), RatLower 3 (-3 / 4), RatUpper 3 0],
     rat_relu_atoms = []\<rparr>"

lemma file_preprocess_mixed_sat_native_initial_basis:
  "map_option (\<lambda>(S, bs, ns). (bs, ns))
     (native_initial_tableau 4 (embed_query file_preprocess_mixed_sat_source)) =
   Some ([2, 1, 3], [0, 4, 5, 6])"
  by code_simp

end
