theory Imported_Marabou_Explained_Negative
  imports "Marabou_Verification.Rational_Proof_Trees"
begin

text \<open>
  Generated by the untrusted Marabou JSON adapter. All numbers below denote
  exact rationals decoded from the serialized decimal tokens. This theorem
  concerns this explicit processed query, not an earlier neural-network input.
  Expected query SHA-256: 4e389aa5c3c01d8e23d078203d6d2b46200ad3f3887ddde03e180935e6151e95
  Certificate SHA-256: a1868711f2caddc43562c8bf6ff839bef611d718afcae11fc4152b37fca983d4
\<close>

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 2), ((-1), 5)]) 0, RatEq (RatExpr 0 [(1, 0), ((-2), 3), (1, 4), ((-1), 6)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 (1 / 4), RatUpper 1 2, RatLower 2 0, RatUpper 2 4, RatLower 3 (-1), RatUpper 3 0, RatLower 4 (1 / 2), RatUpper 4 2, RatLower 5 0, RatUpper 5 0, RatLower 6 0, RatUpper 6 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Linear_Bound (RatUpper 0 (-1 / 2)) [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1]
    (Relu_Upper 0 1 (-1 / 2) 0
      (Linear_Unsat [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))"

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

end
