theory Imported_Marabou_Source_Linear
  imports "Marabou_Verification.Tableau_Auxiliary_Sequence"
begin

text \<open>
  Generated by the untrusted source-query adapter from four captured artifacts.
  Numbers denote exact rationals decoded from serialized decimal tokens.
  The source was captured before initialization; introductions are harness
  proposals recovered from added columns, not a native transformation log.
  The proofs below check reordering, introductions, the independent processed
  query, and the recursive proof. Neither the JSON decoder nor C++ is verified.
  Source query SHA-256: e9a060673c6a255121708afbe2eb5a11089ab809f1e13af1b9c2af32a4d5a7a8
  Introduction list SHA-256: cde7683e318f344597de675cdd09ebcfb705e5b2084db8d7efb405cfb01276c8
  Processed query SHA-256: 5a97073889b9bb367985445742cda4977aef81ff08c592407383e02635612768
  Certificate SHA-256: 37f5a61c79370f5778cefba7b5fa24953747b18d71f204e506a05f6cc9869343
\<close>

definition imported_source_query :: rat_query where
  "imported_source_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 1)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 (1 / 4), RatLower 1 (1 / 2), RatUpper 1 2],
     rat_relu_atoms = []\<rparr>"

definition imported_source_column_query :: rat_query where
  "imported_source_column_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 1)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 (1 / 4), RatLower 1 (1 / 2), RatUpper 1 2],
     rat_relu_atoms = []\<rparr>"

lemma imported_source_term_order:
  "satisfies_query v (embed_query imported_source_column_query) \<longleftrightarrow>
    satisfies_query v (embed_query imported_source_query)"
  by (simp add: imported_source_query_def imported_source_column_query_def
      embed_query_def satisfies_query_def algebra_simps)

definition imported_steps :: "fixed_aux_step list" where
  "imported_steps = [(0, 2)]"

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 1), ((-1), 2)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 (1 / 4), RatLower 1 (1 / 2), RatUpper 1 2, RatLower 2 0, RatUpper 2 0],
     rat_relu_atoms = []\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Linear_Unsat [0, 1, 0, 1, 1, 0, 1, 0]"

lemma imported_steps_match_query:
  "rat_introduce_fixed_aux_sequence imported_source_column_query imported_steps =
    Some imported_query"
  by code_simp

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

lemma imported_source_certificate_checked:
  "check_after_fixed_aux_sequence imported_source_column_query
    imported_steps imported_certificate"
  by (simp add: check_after_fixed_aux_sequence_def imported_steps_match_query
      imported_certificate_checked)

theorem imported_source_equisatisfiable:
  "satisfiable (embed_query imported_query) \<longleftrightarrow>
    satisfiable (embed_query imported_source_query)"
  using fixed_aux_sequence_satisfiable_iff[OF imported_steps_match_query]
  by (simp add: satisfiable_def imported_source_term_order)

theorem imported_source_query_unsatisfiable:
  "unsatisfiable (embed_query imported_source_query)"
proof -
  have "unsatisfiable (embed_query imported_source_column_query)"
    by (rule check_after_fixed_aux_sequence_sound[OF imported_source_certificate_checked])
  then show ?thesis
    by (simp add: unsatisfiable_def satisfiable_def imported_source_term_order)
qed

end
