theory Imported_Marabou_File_Phase_Chain_Unsat
  imports "Marabou_Verification.Tableau_Auxiliary_Sequence"
    "Marabou_Verification.ReLU_Auxiliary_Sequence"
begin

text \<open>
  Generated by the untrusted source-query adapter from four captured artifacts.
  Numbers denote exact rationals decoded from serialized decimal tokens.
  The source was captured before initialization; introductions are harness
  proposals recovered from added columns, not a native transformation log.
  The proofs below check reordering, introductions, the independent processed
  query, and the recursive proof. Neither the JSON decoder nor C++ is verified.
  Source query SHA-256: 8787822e534f424771d36433924bed2bee5df39998b15e9d03e1231d91adf873
  Introduction list SHA-256: 632abb952c0a2e7b2e098ab711bc0ec287bbb7e6bb7005cf424c57f404fba5bb
  Processed query SHA-256: bd1fd6407e836b257ae6851ad559f3c9b16b2135044c5a3fc0669ac7b516bc38
  Certificate SHA-256: 2aed5f88884597c3f26e56faa8b5c41cb3ce609c053f1a042820148eebdf62a0
\<close>

definition imported_source_query :: rat_query where
  "imported_source_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 2), ((-1), 1)]) (-1 / 4), RatEq (RatExpr 0 [(1, 3), ((-1), 4)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 5)]) 0, RatEq (RatExpr 0 [(1, 3), ((-1), 2), ((-1), 6)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 (-1 / 2), RatLower 1 0, RatUpper 1 2, RatLower 2 (-2), RatUpper 2 2, RatLower 3 0, RatUpper 3 2, RatLower 4 (1 / 4), RatUpper 4 2, RatLower 5 0, RatUpper 5 2, RatLower 6 0, RatUpper 6 2],
     rat_relu_atoms = [ReLU 0 1, ReLU 2 3]\<rparr>"

definition imported_source_column_query :: rat_query where
  "imported_source_column_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [((-1), 1), (1, 2)]) (-1 / 4), RatEq (RatExpr 0 [(1, 3), ((-1), 4)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 5)]) 0, RatEq (RatExpr 0 [((-1), 2), (1, 3), ((-1), 6)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 (-1 / 2), RatLower 1 0, RatUpper 1 2, RatLower 2 (-2), RatUpper 2 2, RatLower 3 0, RatUpper 3 2, RatLower 4 (1 / 4), RatUpper 4 2, RatLower 5 0, RatUpper 5 2, RatLower 6 0, RatUpper 6 2],
     rat_relu_atoms = [ReLU 0 1, ReLU 2 3]\<rparr>"

lemma imported_source_term_order:
  "satisfies_query v (embed_query imported_source_column_query) \<longleftrightarrow>
    satisfies_query v (embed_query imported_source_query)"
  by (simp add: imported_source_query_def imported_source_column_query_def
      embed_query_def satisfies_query_def algebra_simps)

definition imported_steps :: "fixed_aux_step list" where
  "imported_steps = [(0, 7), (1, 8), (2, 9), (3, 10)]"

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [((-1), 1), (1, 2), ((-1), 7)]) 0, RatEq (RatExpr 0 [(1, 3), ((-1), 4), ((-1), 8)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 5), ((-1), 9)]) 0, RatEq (RatExpr 0 [((-1), 2), (1, 3), ((-1), 6), ((-1), 10)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 (-1 / 2), RatLower 1 0, RatUpper 1 2, RatLower 2 (-2), RatUpper 2 2, RatLower 3 0, RatUpper 3 2, RatLower 4 (1 / 4), RatUpper 4 2, RatLower 5 0, RatUpper 5 2, RatLower 6 0, RatUpper 6 2, RatLower 7 (-1 / 4), RatUpper 7 (-1 / 4), RatLower 8 0, RatUpper 8 0, RatLower 9 0, RatUpper 9 0, RatLower 10 0, RatUpper 10 0],
     rat_relu_atoms = [ReLU 0 1, ReLU 2 3]\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Relu_Fix_Inactive 0 1 (RatUpper 0 (-1 / 2)) [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    (Linear_Bound (RatLower 2 (-1 / 4)) [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
      (Relu_Aux_Upper 2 3 6 (-1 / 4) (250001 / 1000000) [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
        (Linear_Bound (RatUpper 2 (-1 / 4)) [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
          (Relu_Upper 2 3 (-1 / 4) 0
            (Linear_Unsat [1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1])))))"

lemma imported_steps_match_query:
  "rat_introduce_fixed_aux_sequence imported_source_column_query imported_steps =
    Some imported_query"
  by code_simp

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

lemma imported_source_certificate_checked:
  "check_after_fixed_aux_sequence imported_source_column_query
    imported_steps imported_certificate"
  by (simp add: check_after_fixed_aux_sequence_def imported_steps_match_query
      imported_certificate_checked)

theorem imported_source_equisatisfiable:
  "satisfiable (embed_query imported_query) \<longleftrightarrow>
    satisfiable (embed_query imported_source_query)"
  using fixed_aux_sequence_satisfiable_iff[OF imported_steps_match_query]
  by (simp add: satisfiable_def imported_source_term_order)

theorem imported_source_query_unsatisfiable:
  "unsatisfiable (embed_query imported_source_query)"
proof -
  have "unsatisfiable (embed_query imported_source_column_query)"
    by (rule check_after_fixed_aux_sequence_sound[OF imported_source_certificate_checked])
  then show ?thesis
    by (simp add: unsatisfiable_def satisfiable_def imported_source_term_order)
qed

text \<open>
  Additional native ReLU introduction sequence and independent before-query.
  Each step checks the current query. The whole final result must equal
  imported_source_query, captured independently after the native calls.
  Before-ReLU query SHA-256: 36bf6a4a18f70a9cc1004e951ac70672cf9db7647e8db58f76de0df4938d2db9
  ReLU introduction sequence SHA-256: 064cf4c53e1fd7aa6e2c965865cbe5918e1d86b71bf1ddb244af3d2e667dfdf2
\<close>

definition imported_before_relu_query :: rat_query where
  "imported_before_relu_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 2), ((-1), 1)]) (-1 / 4), RatEq (RatExpr 0 [(1, 3), ((-1), 4)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 (-1 / 2), RatLower 1 0, RatUpper 1 2, RatLower 2 (-2), RatUpper 2 2, RatLower 3 0, RatUpper 3 2, RatLower 4 (1 / 4), RatUpper 4 2],
     rat_relu_atoms = [ReLU 0 1, ReLU 2 3]\<rparr>"

definition imported_relu_steps :: "relu_aux_step list" where
  "imported_relu_steps = [ReLU_Aux_Step 0 1 5 (Some (-2)), ReLU_Aux_Step 2 3 6 (Some (-2))]"

lemma imported_relu_introductions_match_source:
  "rat_introduce_relu_aux_sequence imported_before_relu_query imported_relu_steps =
    Some imported_source_query"
  by code_simp

theorem imported_relu_introductions_equisatisfiable:
  "satisfiable (embed_query imported_source_query) \<longleftrightarrow>
    satisfiable (embed_query imported_before_relu_query)"
  by (rule relu_aux_sequence_satisfiable_iff[OF imported_relu_introductions_match_source])

theorem imported_before_relu_processed_equisatisfiable:
  "satisfiable (embed_query imported_query) \<longleftrightarrow>
    satisfiable (embed_query imported_before_relu_query)"
  using imported_source_equisatisfiable imported_relu_introductions_equisatisfiable by blast

lemma imported_before_relu_certificate_checked:
  "check_after_relu_aux_sequence imported_before_relu_query imported_relu_steps
    imported_steps imported_certificate"
  by code_simp

theorem imported_before_relu_query_unsatisfiable:
  "unsatisfiable (embed_query imported_before_relu_query)"
  by (rule check_after_relu_aux_sequence_sound[OF imported_before_relu_certificate_checked])

end
