theory Imported_Marabou_Source_Relu_Split
  imports "Marabou_Verification.Tableau_Auxiliary_Sequence"
begin

text \<open>
  Generated by the untrusted source-query adapter from four captured artifacts.
  Numbers denote exact rationals decoded from serialized decimal tokens.
  The source was captured before initialization; introductions are harness
  proposals recovered from added columns, not a native transformation log.
  The proofs below check reordering, introductions, the independent processed
  query, and the recursive proof. Neither the JSON decoder nor C++ is verified.
  Source query SHA-256: bb189d900b7453b78897200c9c698823103db1de18ce8beb4f67ccc6a382ec53
  Introduction list SHA-256: b537adfe66eca8721cc6aa6b9b7631a80631a1d7f47c0409140dd211472df476
  Processed query SHA-256: df27a42e43fb65767777bef0387d056e340afbce25f371f75e516153d7b1cfcb
  Certificate SHA-256: 0d5c334f385d725ea28430bb756dc3546ccd4b50459d7bb5cb562fc7d6ecac19
\<close>

definition imported_source_query :: rat_query where
  "imported_source_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 1), ((-1), 3), ((-1), 5)]) (1 / 4), RatEq (RatExpr 0 [(1, 1), (1, 3), ((-1), 6)]) (1 / 4), RatEq (RatExpr 0 [(1, 2), ((-1), 4), ((-1), 7)]) (1 / 4), RatEq (RatExpr 0 [(1, 2), (1, 4), ((-1), 8)]) (1 / 4), RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 2)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 1, RatLower 1 0, RatUpper 1 1, RatLower 2 0, RatUpper 2 1, RatLower 3 (-1), RatUpper 3 1, RatLower 4 (-1), RatUpper 4 1, RatLower 5 0, RatUpper 5 2, RatLower 6 0, RatUpper 6 2, RatLower 7 0, RatUpper 7 2, RatLower 8 0, RatUpper 8 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_source_column_query :: rat_query where
  "imported_source_column_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 1), ((-1), 3), ((-1), 5)]) (1 / 4), RatEq (RatExpr 0 [(1, 1), (1, 3), ((-1), 6)]) (1 / 4), RatEq (RatExpr 0 [(1, 2), ((-1), 4), ((-1), 7)]) (1 / 4), RatEq (RatExpr 0 [(1, 2), (1, 4), ((-1), 8)]) (1 / 4), RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 2)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 1, RatLower 1 0, RatUpper 1 1, RatLower 2 0, RatUpper 2 1, RatLower 3 (-1), RatUpper 3 1, RatLower 4 (-1), RatUpper 4 1, RatLower 5 0, RatUpper 5 2, RatLower 6 0, RatUpper 6 2, RatLower 7 0, RatUpper 7 2, RatLower 8 0, RatUpper 8 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma imported_source_term_order:
  "satisfies_query v (embed_query imported_source_column_query) \<longleftrightarrow>
    satisfies_query v (embed_query imported_source_query)"
  by (simp add: imported_source_query_def imported_source_column_query_def
      embed_query_def satisfies_query_def algebra_simps)

definition imported_steps :: "fixed_aux_step list" where
  "imported_steps = [(0, 9), (1, 10), (2, 11), (3, 12), (4, 13)]"

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 1), ((-1), 3), ((-1), 5), ((-1), 9)]) 0, RatEq (RatExpr 0 [(1, 1), (1, 3), ((-1), 6), ((-1), 10)]) 0, RatEq (RatExpr 0 [(1, 2), ((-1), 4), ((-1), 7), ((-1), 11)]) 0, RatEq (RatExpr 0 [(1, 2), (1, 4), ((-1), 8), ((-1), 12)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 2), ((-1), 13)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 1, RatLower 1 0, RatUpper 1 1, RatLower 2 0, RatUpper 2 1, RatLower 3 (-1), RatUpper 3 1, RatLower 4 (-1), RatUpper 4 1, RatLower 5 0, RatUpper 5 2, RatLower 6 0, RatUpper 6 2, RatLower 7 0, RatUpper 7 2, RatLower 8 0, RatUpper 8 2, RatLower 9 (1 / 4), RatUpper 9 (1 / 4), RatLower 10 (1 / 4), RatUpper 10 (1 / 4), RatLower 11 (1 / 4), RatUpper 11 (1 / 4), RatLower 12 (1 / 4), RatUpper 12 (1 / 4), RatLower 13 0, RatUpper 13 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Relu_Split 0 1
    (Linear_Unsat [2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0])
    (Linear_Unsat [2, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0])"

lemma imported_steps_match_query:
  "rat_introduce_fixed_aux_sequence imported_source_column_query imported_steps =
    Some imported_query"
  by code_simp

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

lemma imported_source_certificate_checked:
  "check_after_fixed_aux_sequence imported_source_column_query
    imported_steps imported_certificate"
  by (simp add: check_after_fixed_aux_sequence_def imported_steps_match_query
      imported_certificate_checked)

theorem imported_source_equisatisfiable:
  "satisfiable (embed_query imported_query) \<longleftrightarrow>
    satisfiable (embed_query imported_source_query)"
  using fixed_aux_sequence_satisfiable_iff[OF imported_steps_match_query]
  by (simp add: satisfiable_def imported_source_term_order)

theorem imported_source_query_unsatisfiable:
  "unsatisfiable (embed_query imported_source_query)"
proof -
  have "unsatisfiable (embed_query imported_source_column_query)"
    by (rule check_after_fixed_aux_sequence_sound[OF imported_source_certificate_checked])
  then show ?thesis
    by (simp add: unsatisfiable_def satisfiable_def imported_source_term_order)
qed

end
