theory Imported_Marabou_File_Phase_Active_Unsat
  imports "Marabou_Verification.Tableau_Auxiliary_Sequence"
    "Marabou_Verification.ReLU_Auxiliary_Sequence"
begin

text \<open>
  Generated by the untrusted source-query adapter from four captured artifacts.
  Numbers denote exact rationals decoded from serialized decimal tokens.
  The source was captured before initialization; introductions are harness
  proposals recovered from added columns, not a native transformation log.
  The proofs below check reordering, introductions, the independent processed
  query, and the recursive proof. Neither the JSON decoder nor C++ is verified.
  Source query SHA-256: 068bb13ba149689d306e73d4e83e667939b1a9310d93f4885a8f6d9898478a2a
  Introduction list SHA-256: dce950c497669dac9675982b0e8872f8f6fbcabd2a8d305c8df23c3d6812c0bf
  Processed query SHA-256: c2d1a3843540d7caf77dac55247c8ffdad95357b5d36e5dac0ba51c688d80ad1
  Certificate SHA-256: fb3298786f94086b67f88107dbb41aa2ddcb9ef33658bd4becbaf4883416cf88
\<close>

definition imported_source_query :: rat_query where
  "imported_source_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 2)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 3)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 1, RatLower 1 (3 / 2), RatUpper 1 2, RatLower 2 (-1), RatUpper 2 1, RatLower 3 0, RatUpper 3 1],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_source_column_query :: rat_query where
  "imported_source_column_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 2)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 3)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 1, RatLower 1 (3 / 2), RatUpper 1 2, RatLower 2 (-1), RatUpper 2 1, RatLower 3 0, RatUpper 3 1],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma imported_source_term_order:
  "satisfies_query v (embed_query imported_source_column_query) \<longleftrightarrow>
    satisfies_query v (embed_query imported_source_query)"
  by (simp add: imported_source_query_def imported_source_column_query_def
      embed_query_def satisfies_query_def algebra_simps)

definition imported_steps :: "fixed_aux_step list" where
  "imported_steps = [(0, 4), (1, 5)]"

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 2), ((-1), 4)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 3), ((-1), 5)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 1, RatLower 1 (3 / 2), RatUpper 1 2, RatLower 2 (-1), RatUpper 2 1, RatLower 3 0, RatUpper 3 1, RatLower 4 0, RatUpper 4 0, RatLower 5 0, RatUpper 5 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Relu_Fix_Active 0 1 (RatLower 1 (3 / 2)) [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    (Linear_Unsat [1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1])"

lemma imported_steps_match_query:
  "rat_introduce_fixed_aux_sequence imported_source_column_query imported_steps =
    Some imported_query"
  by code_simp

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

lemma imported_source_certificate_checked:
  "check_after_fixed_aux_sequence imported_source_column_query
    imported_steps imported_certificate"
  by (simp add: check_after_fixed_aux_sequence_def imported_steps_match_query
      imported_certificate_checked)

theorem imported_source_equisatisfiable:
  "satisfiable (embed_query imported_query) \<longleftrightarrow>
    satisfiable (embed_query imported_source_query)"
  using fixed_aux_sequence_satisfiable_iff[OF imported_steps_match_query]
  by (simp add: satisfiable_def imported_source_term_order)

theorem imported_source_query_unsatisfiable:
  "unsatisfiable (embed_query imported_source_query)"
proof -
  have "unsatisfiable (embed_query imported_source_column_query)"
    by (rule check_after_fixed_aux_sequence_sound[OF imported_source_certificate_checked])
  then show ?thesis
    by (simp add: unsatisfiable_def satisfiable_def imported_source_term_order)
qed

text \<open>
  Additional native ReLU introduction sequence and independent before-query.
  Each step checks the current query. The whole final result must equal
  imported_source_query, captured independently after the native calls.
  Before-ReLU query SHA-256: 39ab7e8ab15c08a1497cb3ed7a3399c7424bee105006b63f9a92851d14202e03
  ReLU introduction sequence SHA-256: cbaddcdff6dbb67da5248ab59f6b2d0f54892e815f113379b221ba3a1681ed65
\<close>

definition imported_before_relu_query :: rat_query where
  "imported_before_relu_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 2)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 1, RatLower 1 (3 / 2), RatUpper 1 2, RatLower 2 (-1), RatUpper 2 1],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_relu_steps :: "relu_aux_step list" where
  "imported_relu_steps = [ReLU_Aux_Step 0 1 3 (Some (-1))]"

lemma imported_relu_introductions_match_source:
  "rat_introduce_relu_aux_sequence imported_before_relu_query imported_relu_steps =
    Some imported_source_query"
  by code_simp

theorem imported_relu_introductions_equisatisfiable:
  "satisfiable (embed_query imported_source_query) \<longleftrightarrow>
    satisfiable (embed_query imported_before_relu_query)"
  by (rule relu_aux_sequence_satisfiable_iff[OF imported_relu_introductions_match_source])

theorem imported_before_relu_processed_equisatisfiable:
  "satisfiable (embed_query imported_query) \<longleftrightarrow>
    satisfiable (embed_query imported_before_relu_query)"
  using imported_source_equisatisfiable imported_relu_introductions_equisatisfiable by blast

lemma imported_before_relu_certificate_checked:
  "check_after_relu_aux_sequence imported_before_relu_query imported_relu_steps
    imported_steps imported_certificate"
  by code_simp

theorem imported_before_relu_query_unsatisfiable:
  "unsatisfiable (embed_query imported_before_relu_query)"
  by (rule check_after_relu_aux_sequence_sound[OF imported_before_relu_certificate_checked])

end
