theory Imported_Marabou_Source_Relu
  imports "Marabou_Verification.Tableau_Auxiliary_Sequence"
begin

text \<open>
  Generated by the untrusted source-query adapter from four captured artifacts.
  Numbers denote exact rationals decoded from serialized decimal tokens.
  The source was captured before initialization; introductions are harness
  proposals recovered from added columns, not a native transformation log.
  The proofs below check reordering, introductions, the independent processed
  query, and the recursive proof. Neither the JSON decoder nor C++ is verified.
  Source query SHA-256: d7117b9a0275fcb31bcefb70cd176d37545e3a482b82e1c742b3fd22a29919cb
  Introduction list SHA-256: 8b0d136f369b128f79fac0286d25e9fd05e1bbe9ac560c7df1b44b454d53f9aa
  Processed query SHA-256: 5d3f878353206a4001bd31125ae824fd71d6ba7966fa104dc563c9617c5a9c60
  Certificate SHA-256: 02869556f899e7b67b9a6735fac5e350bedac1b602feb46a98bfd0c9cf24a926
\<close>

definition imported_source_query :: rat_query where
  "imported_source_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 2)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 4)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 3)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 (-1), RatUpper 2 (-1 / 2), RatLower 3 (1 / 4), RatUpper 3 2, RatLower 4 0, RatUpper 4 1],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_source_column_query :: rat_query where
  "imported_source_column_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 2)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 4)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 3)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 (-1), RatUpper 2 (-1 / 2), RatLower 3 (1 / 4), RatUpper 3 2, RatLower 4 0, RatUpper 4 1],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma imported_source_term_order:
  "satisfies_query v (embed_query imported_source_column_query) \<longleftrightarrow>
    satisfies_query v (embed_query imported_source_query)"
  by (simp add: imported_source_query_def imported_source_column_query_def
      embed_query_def satisfies_query_def algebra_simps)

definition imported_steps :: "fixed_aux_step list" where
  "imported_steps = [(0, 5), (1, 6), (2, 7)]"

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 2), ((-1), 5)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 4), ((-1), 6)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 3), ((-1), 7)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 (-1), RatUpper 2 (-1 / 2), RatLower 3 (1 / 4), RatUpper 3 2, RatLower 4 0, RatUpper 4 1, RatLower 5 0, RatUpper 5 0, RatLower 6 0, RatUpper 6 0, RatLower 7 0, RatUpper 7 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Linear_Bound (RatUpper 0 (-1 / 2)) [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
    (Relu_Upper 0 1 (-1 / 2) 0
      (Linear_Unsat [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0]))"

lemma imported_steps_match_query:
  "rat_introduce_fixed_aux_sequence imported_source_column_query imported_steps =
    Some imported_query"
  by code_simp

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

lemma imported_source_certificate_checked:
  "check_after_fixed_aux_sequence imported_source_column_query
    imported_steps imported_certificate"
  by (simp add: check_after_fixed_aux_sequence_def imported_steps_match_query
      imported_certificate_checked)

theorem imported_source_equisatisfiable:
  "satisfiable (embed_query imported_query) \<longleftrightarrow>
    satisfiable (embed_query imported_source_query)"
  using fixed_aux_sequence_satisfiable_iff[OF imported_steps_match_query]
  by (simp add: satisfiable_def imported_source_term_order)

theorem imported_source_query_unsatisfiable:
  "unsatisfiable (embed_query imported_source_query)"
proof -
  have "unsatisfiable (embed_query imported_source_column_query)"
    by (rule check_after_fixed_aux_sequence_sound[OF imported_source_certificate_checked])
  then show ?thesis
    by (simp add: unsatisfiable_def satisfiable_def imported_source_term_order)
qed

end
