theory Imported_Marabou_Native_Relu_Sat
  imports "Marabou_Verification.Rational_Assignment"
begin

text \<open>
  Generated by the untrusted assignment adapter. Query numbers denote exact
  rationals decoded from serialized decimal tokens. Assignment values are the
  exact binary values of the native doubles.
  The code_simp proofs below check every linear atom, bound and ReLU exactly;
  the reconstruction itself is not trusted. The C++ solver, extraction and
  JSON decoding are not verified.
  Before-ReLU query SHA-256: a585ffc093dd973aaf01c9fca87f9d72b6dab6649950844307a79390f073a82d
  ReLU introduction sequence SHA-256: cc81ae05eb801ce40baa8171fdb96e63645772c1cd58099eac624c2ba18443b4
  Source query SHA-256: b323a2bd2dd3a8b440a16df0df5d4abbf84fb130a74d7f25ba1347495a453616
  Introduction list SHA-256: b537adfe66eca8721cc6aa6b9b7631a80631a1d7f47c0409140dd211472df476
  Processed query SHA-256: 137e6ea6f66d6cbdca0b7b56d6daa9559daf5162441f91724893b3f1130b474e
  Native assignment SHA-256: b481582713462db521bca92f5c74750b41f9156117b18cadfd9d400ce7dd76d7
\<close>

definition imported_source_query :: rat_query where
  "imported_source_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 4)]) 0, RatEq (RatExpr 0 [(1, 2), ((-1), 5)]) 0, RatEq (RatExpr 0 [(1, 1), (1, 3), ((-1), 6)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 7)]) 0, RatEq (RatExpr 0 [(1, 3), ((-1), 2), ((-1), 8)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 (-2), RatUpper 2 2, RatLower 3 0, RatUpper 3 2, RatLower 4 (1 / 2), RatUpper 4 2, RatLower 5 (-2), RatUpper 5 (-1 / 4), RatLower 6 0, RatUpper 6 1, RatLower 7 0, RatUpper 7 2, RatLower 8 0, RatUpper 8 2],
     rat_relu_atoms = [ReLU 0 1, ReLU 2 3]\<rparr>"

definition imported_source_column_query :: rat_query where
  "imported_source_column_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 4)]) 0, RatEq (RatExpr 0 [(1, 2), ((-1), 5)]) 0, RatEq (RatExpr 0 [(1, 1), (1, 3), ((-1), 6)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 7)]) 0, RatEq (RatExpr 0 [((-1), 2), (1, 3), ((-1), 8)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 (-2), RatUpper 2 2, RatLower 3 0, RatUpper 3 2, RatLower 4 (1 / 2), RatUpper 4 2, RatLower 5 (-2), RatUpper 5 (-1 / 4), RatLower 6 0, RatUpper 6 1, RatLower 7 0, RatUpper 7 2, RatLower 8 0, RatUpper 8 2],
     rat_relu_atoms = [ReLU 0 1, ReLU 2 3]\<rparr>"

lemma imported_source_term_order:
  "satisfies_query v (embed_query imported_source_column_query) \<longleftrightarrow>
    satisfies_query v (embed_query imported_source_query)"
  by (simp add: imported_source_query_def imported_source_column_query_def
      embed_query_def satisfies_query_def algebra_simps)

definition imported_steps :: "fixed_aux_step list" where
  "imported_steps = [(0, 9), (1, 10), (2, 11), (3, 12), (4, 13)]"

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 4), ((-1), 9)]) 0, RatEq (RatExpr 0 [(1, 2), ((-1), 5), ((-1), 10)]) 0, RatEq (RatExpr 0 [(1, 1), (1, 3), ((-1), 6), ((-1), 11)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 7), ((-1), 12)]) 0, RatEq (RatExpr 0 [((-1), 2), (1, 3), ((-1), 8), ((-1), 13)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 (-2), RatUpper 2 2, RatLower 3 0, RatUpper 3 2, RatLower 4 (1 / 2), RatUpper 4 2, RatLower 5 (-2), RatUpper 5 (-1 / 4), RatLower 6 0, RatUpper 6 1, RatLower 7 0, RatUpper 7 2, RatLower 8 0, RatUpper 8 2, RatLower 9 0, RatUpper 9 0, RatLower 10 0, RatUpper 10 0, RatLower 11 0, RatUpper 11 0, RatLower 12 0, RatUpper 12 0, RatLower 13 0, RatUpper 13 0],
     rat_relu_atoms = [ReLU 0 1, ReLU 2 3]\<rparr>"

definition imported_assignment :: rat_assignment where
  "imported_assignment = [(0, (1 / 2)), (1, (1 / 2)), (2, (-2)), (3, 0), (4, (1 / 2)), (5, (-2)), (6, (1 / 2)), (7, 0), (8, 2), (9, 0), (10, 0), (11, 0), (12, 0), (13, 0)]"

lemma imported_steps_match_query:
  "rat_introduce_fixed_aux_sequence imported_source_column_query imported_steps =
    Some imported_query"
  by code_simp

lemma imported_assignment_checked:
  "check_rat_assignment imported_query imported_assignment"
  by code_simp

theorem imported_query_model:
  "satisfies_query (assignment_valuation imported_assignment) (embed_query imported_query)"
  by (rule check_rat_assignment_sound[OF imported_assignment_checked])

theorem imported_query_satisfiable:
  "satisfiable (embed_query imported_query)"
  by (rule check_rat_assignment_satisfiable[OF imported_assignment_checked])

lemma imported_source_assignment_checked:
  "check_rat_assignment imported_source_query imported_assignment"
  by code_simp

theorem imported_source_query_model:
  "satisfies_query (assignment_valuation imported_assignment) (embed_query imported_source_query)"
  by (rule check_rat_assignment_sound[OF imported_source_assignment_checked])

theorem imported_source_query_satisfiable_via_processed:
  "satisfiable (embed_query imported_source_query)"
proof -
  have "satisfiable (embed_query imported_source_column_query)"
    by (rule fixed_aux_sequence_assignment_satisfiable[OF imported_steps_match_query
          imported_assignment_checked])
  then show ?thesis by (simp add: satisfiable_def imported_source_term_order)
qed

definition imported_before_relu_query :: rat_query where
  "imported_before_relu_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 4)]) 0, RatEq (RatExpr 0 [(1, 2), ((-1), 5)]) 0, RatEq (RatExpr 0 [(1, 1), (1, 3), ((-1), 6)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 (-2), RatUpper 2 2, RatLower 3 0, RatUpper 3 2, RatLower 4 (1 / 2), RatUpper 4 2, RatLower 5 (-2), RatUpper 5 (-1 / 4), RatLower 6 0, RatUpper 6 1],
     rat_relu_atoms = [ReLU 0 1, ReLU 2 3]\<rparr>"

definition imported_relu_steps :: "relu_aux_step list" where
  "imported_relu_steps = [ReLU_Aux_Step 0 1 7 (Some (-2)), ReLU_Aux_Step 2 3 8 (Some (-2))]"

lemma imported_relu_introductions_match_source:
  "rat_introduce_relu_aux_sequence imported_before_relu_query imported_relu_steps =
    Some imported_source_query"
  by code_simp

lemma imported_before_relu_assignment_checked:
  "check_rat_assignment imported_before_relu_query imported_assignment"
  by code_simp

theorem imported_before_relu_query_model:
  "satisfies_query (assignment_valuation imported_assignment)
    (embed_query imported_before_relu_query)"
  by (rule check_rat_assignment_sound[OF imported_before_relu_assignment_checked])

theorem imported_before_relu_query_satisfiable_via_processed:
  "satisfiable (embed_query imported_before_relu_query)"
  using relu_aux_sequence_satisfiable_iff[OF imported_relu_introductions_match_source]
    imported_source_query_satisfiable_via_processed
  by blast

end
