theory Imported_Marabou_Prepared_Inequality_Linear_Sat
  imports "Marabou_Verification.Rational_Assignment"
begin

text \<open>
  Generated by the untrusted assignment adapter. Query numbers denote exact
  rationals decoded from serialized decimal tokens. Assignment values are the
  exact binary values of the native doubles.
  The code_simp proofs below check every linear atom, bound and ReLU exactly;
  the reconstruction itself is not trusted. The C++ solver, extraction and
  JSON decoding are not verified.
  Source query SHA-256: 4a062038263be8089af0146e9d5fced7efd273102f6f8cba9c9df6e839010354
  Introduction list SHA-256: bc49741d64ab72fcb7917f41c3364c3ecbc056a03ba63d20633e57dab03a1b81
  Processed query SHA-256: ff7ca538427bc0e1e03380837b1ded998c6745d5d5ee8adddbc6aeea96fa0dc3
  Native assignment SHA-256: b6b0b1b0cbea2f5c3bea9d390ded78dab430a1af62eff614bead0a020bf0df93
\<close>

definition imported_source_query :: rat_query where
  "imported_source_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 1), (1, 2)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 1, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 4],
     rat_relu_atoms = []\<rparr>"

definition imported_source_column_query :: rat_query where
  "imported_source_column_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 1), (1, 2)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 1, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 4],
     rat_relu_atoms = []\<rparr>"

lemma imported_source_term_order:
  "satisfies_query v (embed_query imported_source_column_query) \<longleftrightarrow>
    satisfies_query v (embed_query imported_source_query)"
  by (simp add: imported_source_query_def imported_source_column_query_def
      embed_query_def satisfies_query_def algebra_simps)

definition imported_steps :: "fixed_aux_step list" where
  "imported_steps = [(0, 3)]"

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 1), (1, 2), ((-1), 3)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 1, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 4, RatLower 3 0, RatUpper 3 0],
     rat_relu_atoms = []\<rparr>"

definition imported_assignment :: rat_assignment where
  "imported_assignment = [(0, 0), (1, 0), (2, 0), (3, 0)]"

lemma imported_steps_match_query:
  "rat_introduce_fixed_aux_sequence imported_source_column_query imported_steps =
    Some imported_query"
  by code_simp

lemma imported_assignment_checked:
  "check_rat_assignment imported_query imported_assignment"
  by code_simp

theorem imported_query_model:
  "satisfies_query (assignment_valuation imported_assignment) (embed_query imported_query)"
  by (rule check_rat_assignment_sound[OF imported_assignment_checked])

theorem imported_query_satisfiable:
  "satisfiable (embed_query imported_query)"
  by (rule check_rat_assignment_satisfiable[OF imported_assignment_checked])

lemma imported_source_assignment_checked:
  "check_rat_assignment imported_source_query imported_assignment"
  by code_simp

theorem imported_source_query_model:
  "satisfies_query (assignment_valuation imported_assignment) (embed_query imported_source_query)"
  by (rule check_rat_assignment_sound[OF imported_source_assignment_checked])

theorem imported_source_query_satisfiable_via_processed:
  "satisfiable (embed_query imported_source_query)"
proof -
  have "satisfiable (embed_query imported_source_column_query)"
    by (rule fixed_aux_sequence_assignment_satisfiable[OF imported_steps_match_query
          imported_assignment_checked])
  then show ?thesis by (simp add: satisfiable_def imported_source_term_order)
qed

end
