theory Imported_Marabou_Solver_Relu_Aux
  imports "Marabou_Verification.Rational_Proof_Trees"
begin

text \<open>
  Generated by the untrusted Marabou JSON adapter. All numbers below denote
  exact rationals decoded from the serialized decimal tokens. This theorem
  concerns this explicit processed query, not an earlier neural-network input.
  Expected query SHA-256: 05b4095b8b12a8f51c28d16304953ea9145360067281a8157cda8dadb23f07e9
  Certificate SHA-256: 83a88cab09d7dcd0aeddb0c35d7679956caa775fc0b20fdd1999241d95b6a5cf
\<close>

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 2), ((-1), 5)]) 0, RatEq (RatExpr 0 [(1, 1), ((-1), 3), ((-1), 6)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 4), ((-1), 7)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 (-2), RatUpper 2 (-1 / 2), RatLower 3 (1 / 4), RatUpper 3 2, RatLower 4 0, RatUpper 4 2, RatLower 5 0, RatUpper 5 0, RatLower 6 0, RatUpper 6 0, RatLower 7 0, RatUpper 7 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Linear_Bound (RatLower 0 (-7 / 4)) [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1]
    (Relu_Aux_Upper 0 1 4 (-7 / 4) (875001 / 500000) [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
      [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
      (Linear_Bound (RatUpper 0 (-1 / 2)) [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
        (Relu_Upper 0 1 (-1 / 2) 0
          (Linear_Unsat [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0]))))"

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

end
