theory Imported_Marabou_Exact_Texts
  imports Exact_Query_Format
    Imported_Marabou_Source_Linear
    Imported_Marabou_Source_Relu
    Imported_Marabou_Source_Relu_Aux
    Imported_Marabou_Source_Relu_Aux_Active
    Imported_Marabou_Source_Relu_Aux_Inactive
    Imported_Marabou_Source_Relu_Split
    Imported_Marabou_Native_Relu_Intro
    Imported_Marabou_Native_Relu_Sequence
    Imported_Marabou_Native_Relu_Chain
    Imported_Marabou_Native_Relu_Sat
begin

text \<open>
  Generated by the untrusted exporter tools/exact_query_text.py. Each byte list
  is the exact content of a saved .mqx fixture: the build reads each declared
  file and fails unless it equals the defined bytes. The
  format's meaning is decode_query, and each decoding is proved by code_simp
  to be the explicit starting query of the named capture. The theorems below
  therefore concern the decoded bytes. The C++ solver, the capture of the
  JSON snapshot and the exporter itself are not verified or trusted.
\<close>

text \<open>
  Bytes of tests/fixtures/marabou/solver_linear.mqx
  (90 bytes, SHA-256 3f016cc0967d6d1ed7524dfde41fcf38b74771e80159b5a15b351fe02f637b3d).
\<close>

definition solver_linear_text :: bytes where
  "solver_linear_text = [109, 97, 114, 97, 98, 111, 117, 45, 101, 120, 97, 99, 116, 45, 113, 117, 101, 114, 121, 45, 118, 49, 10, 101,
    113, 32, 49, 32, 120, 48, 32, 45, 49, 32, 120, 49, 32, 61, 32, 48, 10, 108, 111, 119, 101, 114, 32, 120,
    48, 32, 45, 50, 10, 117, 112, 112, 101, 114, 32, 120, 48, 32, 49, 47, 52, 10, 108, 111, 119, 101, 114, 32,
    120, 49, 32, 49, 47, 50, 10, 117, 112, 112, 101, 114, 32, 120, 49, 32, 50, 10]"

external_file "tests/fixtures/marabou/solver_linear.mqx"

ML \<open>
  Exact_Query_Text.check_file \<^theory> @{thm solver_linear_text_def}
    "tests/fixtures/marabou/solver_linear.mqx"
\<close>

lemma solver_linear_text_decodes:
  "decode_query solver_linear_text = Some Imported_Marabou_Source_Linear.imported_source_query"
  by code_simp

theorem solver_linear_text_unsatisfiable:
  "decode_query solver_linear_text = Some Q \<Longrightarrow> unsatisfiable (embed_query Q)"
  using solver_linear_text_decodes Imported_Marabou_Source_Linear.imported_source_query_unsatisfiable by simp

text \<open>
  Bytes of tests/fixtures/marabou/solver_relu.mqx
  (211 bytes, SHA-256 33d523e9f505730b3083a757154d7f6337d9ddcaec4d639671e0dd679f21bc89).
\<close>

definition solver_relu_text :: bytes where
  "solver_relu_text = [109, 97, 114, 97, 98, 111, 117, 45, 101, 120, 97, 99, 116, 45, 113, 117, 101, 114, 121, 45, 118, 49, 10, 101,
    113, 32, 49, 32, 120, 48, 32, 45, 49, 32, 120, 50, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 49,
    32, 45, 49, 32, 120, 48, 32, 45, 49, 32, 120, 52, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 49,
    32, 45, 49, 32, 120, 51, 32, 61, 32, 48, 10, 108, 111, 119, 101, 114, 32, 120, 48, 32, 45, 49, 10, 117,
    112, 112, 101, 114, 32, 120, 48, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 49, 32, 48, 10, 117, 112, 112,
    101, 114, 32, 120, 49, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 50, 32, 45, 49, 10, 117, 112, 112, 101,
    114, 32, 120, 50, 32, 45, 49, 47, 50, 10, 108, 111, 119, 101, 114, 32, 120, 51, 32, 49, 47, 52, 10, 117,
    112, 112, 101, 114, 32, 120, 51, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 52, 32, 48, 10, 117, 112, 112,
    101, 114, 32, 120, 52, 32, 49, 10, 114, 101, 108, 117, 32, 120, 48, 32, 120, 49, 10]"

external_file "tests/fixtures/marabou/solver_relu.mqx"

ML \<open>
  Exact_Query_Text.check_file \<^theory> @{thm solver_relu_text_def}
    "tests/fixtures/marabou/solver_relu.mqx"
\<close>

lemma solver_relu_text_decodes:
  "decode_query solver_relu_text = Some Imported_Marabou_Source_Relu.imported_source_query"
  by code_simp

theorem solver_relu_text_unsatisfiable:
  "decode_query solver_relu_text = Some Q \<Longrightarrow> unsatisfiable (embed_query Q)"
  using solver_relu_text_decodes Imported_Marabou_Source_Relu.imported_source_query_unsatisfiable by simp

text \<open>
  Bytes of tests/fixtures/marabou/solver_relu_aux.mqx
  (211 bytes, SHA-256 bb6b55322fb674d76a04af97cb1914f22cad56637c3d525055369b7bbfcb97f6).
\<close>

definition solver_relu_aux_text :: bytes where
  "solver_relu_aux_text = [109, 97, 114, 97, 98, 111, 117, 45, 101, 120, 97, 99, 116, 45, 113, 117, 101, 114, 121, 45, 118, 49, 10, 101,
    113, 32, 49, 32, 120, 48, 32, 45, 49, 32, 120, 50, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 49,
    32, 45, 49, 32, 120, 51, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 49, 32, 45, 49, 32, 120, 48,
    32, 45, 49, 32, 120, 52, 32, 61, 32, 48, 10, 108, 111, 119, 101, 114, 32, 120, 48, 32, 45, 50, 10, 117,
    112, 112, 101, 114, 32, 120, 48, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 49, 32, 48, 10, 117, 112, 112,
    101, 114, 32, 120, 49, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 50, 32, 45, 50, 10, 117, 112, 112, 101,
    114, 32, 120, 50, 32, 45, 49, 47, 50, 10, 108, 111, 119, 101, 114, 32, 120, 51, 32, 49, 47, 52, 10, 117,
    112, 112, 101, 114, 32, 120, 51, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 52, 32, 48, 10, 117, 112, 112,
    101, 114, 32, 120, 52, 32, 50, 10, 114, 101, 108, 117, 32, 120, 48, 32, 120, 49, 10]"

external_file "tests/fixtures/marabou/solver_relu_aux.mqx"

ML \<open>
  Exact_Query_Text.check_file \<^theory> @{thm solver_relu_aux_text_def}
    "tests/fixtures/marabou/solver_relu_aux.mqx"
\<close>

lemma solver_relu_aux_text_decodes:
  "decode_query solver_relu_aux_text = Some Imported_Marabou_Source_Relu_Aux.imported_source_query"
  by code_simp

theorem solver_relu_aux_text_unsatisfiable:
  "decode_query solver_relu_aux_text = Some Q \<Longrightarrow> unsatisfiable (embed_query Q)"
  using solver_relu_aux_text_decodes Imported_Marabou_Source_Relu_Aux.imported_source_query_unsatisfiable by simp

text \<open>
  Bytes of tests/fixtures/marabou/solver_relu_aux_active.mqx
  (209 bytes, SHA-256 2d332383a8f3c1c13d3d3e1380b4d2005dcb7f37b3a1c6c20e317cedd8478074).
\<close>

definition solver_relu_aux_active_text :: bytes where
  "solver_relu_aux_active_text = [109, 97, 114, 97, 98, 111, 117, 45, 101, 120, 97, 99, 116, 45, 113, 117, 101, 114, 121, 45, 118, 49, 10, 101,
    113, 32, 49, 32, 120, 48, 32, 45, 49, 32, 120, 50, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 52,
    32, 45, 49, 32, 120, 51, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 49, 32, 45, 49, 32, 120, 48,
    32, 45, 49, 32, 120, 52, 32, 61, 32, 48, 10, 108, 111, 119, 101, 114, 32, 120, 48, 32, 45, 49, 10, 117,
    112, 112, 101, 114, 32, 120, 48, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 49, 32, 48, 10, 117, 112, 112,
    101, 114, 32, 120, 49, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 50, 32, 49, 47, 50, 10, 117, 112, 112,
    101, 114, 32, 120, 50, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 51, 32, 49, 47, 52, 10, 117, 112, 112,
    101, 114, 32, 120, 51, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 52, 32, 48, 10, 117, 112, 112, 101, 114,
    32, 120, 52, 32, 50, 10, 114, 101, 108, 117, 32, 120, 48, 32, 120, 49, 10]"

external_file "tests/fixtures/marabou/solver_relu_aux_active.mqx"

ML \<open>
  Exact_Query_Text.check_file \<^theory> @{thm solver_relu_aux_active_text_def}
    "tests/fixtures/marabou/solver_relu_aux_active.mqx"
\<close>

lemma solver_relu_aux_active_text_decodes:
  "decode_query solver_relu_aux_active_text = Some Imported_Marabou_Source_Relu_Aux_Active.imported_source_query"
  by code_simp

theorem solver_relu_aux_active_text_unsatisfiable:
  "decode_query solver_relu_aux_active_text = Some Q \<Longrightarrow> unsatisfiable (embed_query Q)"
  using solver_relu_aux_active_text_decodes Imported_Marabou_Source_Relu_Aux_Active.imported_source_query_unsatisfiable by simp

text \<open>
  Bytes of tests/fixtures/marabou/solver_relu_aux_inactive.mqx
  (209 bytes, SHA-256 98db44f79844b92f424e8105d97a8aad7a148658054ef53ce7de85a29e4873da).
\<close>

definition solver_relu_aux_inactive_text :: bytes where
  "solver_relu_aux_inactive_text = [109, 97, 114, 97, 98, 111, 117, 45, 101, 120, 97, 99, 116, 45, 113, 117, 101, 114, 121, 45, 118, 49, 10, 101,
    113, 32, 49, 32, 120, 48, 32, 45, 49, 32, 120, 51, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 50,
    32, 45, 49, 32, 120, 52, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 50, 32, 45, 49, 32, 120, 49,
    32, 45, 49, 32, 120, 48, 32, 61, 32, 48, 10, 108, 111, 119, 101, 114, 32, 120, 48, 32, 48, 10, 117, 112,
    112, 101, 114, 32, 120, 48, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 49, 32, 45, 50, 10, 117, 112, 112,
    101, 114, 32, 120, 49, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 50, 32, 48, 10, 117, 112, 112, 101, 114,
    32, 120, 50, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 51, 32, 49, 47, 52, 10, 117, 112, 112, 101, 114,
    32, 120, 51, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 52, 32, 49, 47, 52, 10, 117, 112, 112, 101, 114,
    32, 120, 52, 32, 50, 10, 114, 101, 108, 117, 32, 120, 49, 32, 120, 50, 10]"

external_file "tests/fixtures/marabou/solver_relu_aux_inactive.mqx"

ML \<open>
  Exact_Query_Text.check_file \<^theory> @{thm solver_relu_aux_inactive_text_def}
    "tests/fixtures/marabou/solver_relu_aux_inactive.mqx"
\<close>

lemma solver_relu_aux_inactive_text_decodes:
  "decode_query solver_relu_aux_inactive_text = Some Imported_Marabou_Source_Relu_Aux_Inactive.imported_source_query"
  by code_simp

theorem solver_relu_aux_inactive_text_unsatisfiable:
  "decode_query solver_relu_aux_inactive_text = Some Q \<Longrightarrow> unsatisfiable (embed_query Q)"
  using solver_relu_aux_inactive_text_decodes Imported_Marabou_Source_Relu_Aux_Inactive.imported_source_query_unsatisfiable by simp

text \<open>
  Bytes of tests/fixtures/marabou/solver_relu_split.mqx
  (361 bytes, SHA-256 634517b2cb255a06476d931794a9b1fe286cd7d92b0f4c63d190be27c1784aeb).
\<close>

definition solver_relu_split_text :: bytes where
  "solver_relu_split_text = [109, 97, 114, 97, 98, 111, 117, 45, 101, 120, 97, 99, 116, 45, 113, 117, 101, 114, 121, 45, 118, 49, 10, 101,
    113, 32, 49, 32, 120, 49, 32, 45, 49, 32, 120, 51, 32, 45, 49, 32, 120, 53, 32, 61, 32, 49, 47, 52,
    10, 101, 113, 32, 49, 32, 120, 49, 32, 49, 32, 120, 51, 32, 45, 49, 32, 120, 54, 32, 61, 32, 49, 47,
    52, 10, 101, 113, 32, 49, 32, 120, 50, 32, 45, 49, 32, 120, 52, 32, 45, 49, 32, 120, 55, 32, 61, 32,
    49, 47, 52, 10, 101, 113, 32, 49, 32, 120, 50, 32, 49, 32, 120, 52, 32, 45, 49, 32, 120, 56, 32, 61,
    32, 49, 47, 52, 10, 101, 113, 32, 49, 32, 120, 49, 32, 45, 49, 32, 120, 48, 32, 45, 49, 32, 120, 50,
    32, 61, 32, 48, 10, 108, 111, 119, 101, 114, 32, 120, 48, 32, 45, 49, 10, 117, 112, 112, 101, 114, 32, 120,
    48, 32, 49, 10, 108, 111, 119, 101, 114, 32, 120, 49, 32, 48, 10, 117, 112, 112, 101, 114, 32, 120, 49, 32,
    49, 10, 108, 111, 119, 101, 114, 32, 120, 50, 32, 48, 10, 117, 112, 112, 101, 114, 32, 120, 50, 32, 49, 10,
    108, 111, 119, 101, 114, 32, 120, 51, 32, 45, 49, 10, 117, 112, 112, 101, 114, 32, 120, 51, 32, 49, 10, 108,
    111, 119, 101, 114, 32, 120, 52, 32, 45, 49, 10, 117, 112, 112, 101, 114, 32, 120, 52, 32, 49, 10, 108, 111,
    119, 101, 114, 32, 120, 53, 32, 48, 10, 117, 112, 112, 101, 114, 32, 120, 53, 32, 50, 10, 108, 111, 119, 101,
    114, 32, 120, 54, 32, 48, 10, 117, 112, 112, 101, 114, 32, 120, 54, 32, 50, 10, 108, 111, 119, 101, 114, 32,
    120, 55, 32, 48, 10, 117, 112, 112, 101, 114, 32, 120, 55, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 56,
    32, 48, 10, 117, 112, 112, 101, 114, 32, 120, 56, 32, 50, 10, 114, 101, 108, 117, 32, 120, 48, 32, 120, 49,
    10]"

external_file "tests/fixtures/marabou/solver_relu_split.mqx"

ML \<open>
  Exact_Query_Text.check_file \<^theory> @{thm solver_relu_split_text_def}
    "tests/fixtures/marabou/solver_relu_split.mqx"
\<close>

lemma solver_relu_split_text_decodes:
  "decode_query solver_relu_split_text = Some Imported_Marabou_Source_Relu_Split.imported_source_query"
  by code_simp

theorem solver_relu_split_text_unsatisfiable:
  "decode_query solver_relu_split_text = Some Q \<Longrightarrow> unsatisfiable (embed_query Q)"
  using solver_relu_split_text_decodes Imported_Marabou_Source_Relu_Split.imported_source_query_unsatisfiable by simp

text \<open>
  Bytes of tests/fixtures/marabou/solver_relu_intro.mqx
  (165 bytes, SHA-256 e61c5d4040c9d1b6cf53025da0244c91f974189293d64bfe7470f0f9060b9a2f).
\<close>

definition solver_relu_intro_text :: bytes where
  "solver_relu_intro_text = [109, 97, 114, 97, 98, 111, 117, 45, 101, 120, 97, 99, 116, 45, 113, 117, 101, 114, 121, 45, 118, 49, 10, 101,
    113, 32, 49, 32, 120, 48, 32, 45, 49, 32, 120, 50, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 49,
    32, 45, 49, 32, 120, 51, 32, 61, 32, 48, 10, 108, 111, 119, 101, 114, 32, 120, 48, 32, 45, 50, 10, 117,
    112, 112, 101, 114, 32, 120, 48, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 49, 32, 48, 10, 117, 112, 112,
    101, 114, 32, 120, 49, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 50, 32, 45, 50, 10, 117, 112, 112, 101,
    114, 32, 120, 50, 32, 45, 49, 47, 50, 10, 108, 111, 119, 101, 114, 32, 120, 51, 32, 49, 47, 52, 10, 117,
    112, 112, 101, 114, 32, 120, 51, 32, 50, 10, 114, 101, 108, 117, 32, 120, 48, 32, 120, 49, 10]"

external_file "tests/fixtures/marabou/solver_relu_intro.mqx"

ML \<open>
  Exact_Query_Text.check_file \<^theory> @{thm solver_relu_intro_text_def}
    "tests/fixtures/marabou/solver_relu_intro.mqx"
\<close>

lemma solver_relu_intro_text_decodes:
  "decode_query solver_relu_intro_text = Some Imported_Marabou_Native_Relu_Intro.imported_before_relu_query"
  by code_simp

theorem solver_relu_intro_text_unsatisfiable:
  "decode_query solver_relu_intro_text = Some Q \<Longrightarrow> unsatisfiable (embed_query Q)"
  using solver_relu_intro_text_decodes Imported_Marabou_Native_Relu_Intro.imported_before_relu_query_unsatisfiable by simp

text \<open>
  Bytes of tests/fixtures/marabou/solver_relu_sequence.mqx
  (244 bytes, SHA-256 b8d0c0d8e508a3fa333a65facb95d05c632436a52e53fc64f0ecc5e912bd0feb).
\<close>

definition solver_relu_sequence_text :: bytes where
  "solver_relu_sequence_text = [109, 97, 114, 97, 98, 111, 117, 45, 101, 120, 97, 99, 116, 45, 113, 117, 101, 114, 121, 45, 118, 49, 10, 101,
    113, 32, 49, 32, 120, 48, 32, 45, 49, 32, 120, 52, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 50,
    32, 45, 49, 32, 120, 52, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 49, 32, 49, 32, 120, 51, 32,
    45, 49, 32, 120, 53, 32, 61, 32, 48, 10, 108, 111, 119, 101, 114, 32, 120, 48, 32, 45, 50, 10, 117, 112,
    112, 101, 114, 32, 120, 48, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 49, 32, 48, 10, 117, 112, 112, 101,
    114, 32, 120, 49, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 50, 32, 45, 50, 10, 117, 112, 112, 101, 114,
    32, 120, 50, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 51, 32, 48, 10, 117, 112, 112, 101, 114, 32, 120,
    51, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 52, 32, 45, 50, 10, 117, 112, 112, 101, 114, 32, 120, 52,
    32, 45, 49, 47, 50, 10, 108, 111, 119, 101, 114, 32, 120, 53, 32, 49, 47, 52, 10, 117, 112, 112, 101, 114,
    32, 120, 53, 32, 50, 10, 114, 101, 108, 117, 32, 120, 48, 32, 120, 49, 10, 114, 101, 108, 117, 32, 120, 50,
    32, 120, 51, 10]"

external_file "tests/fixtures/marabou/solver_relu_sequence.mqx"

ML \<open>
  Exact_Query_Text.check_file \<^theory> @{thm solver_relu_sequence_text_def}
    "tests/fixtures/marabou/solver_relu_sequence.mqx"
\<close>

lemma solver_relu_sequence_text_decodes:
  "decode_query solver_relu_sequence_text = Some Imported_Marabou_Native_Relu_Sequence.imported_before_relu_query"
  by code_simp

theorem solver_relu_sequence_text_unsatisfiable:
  "decode_query solver_relu_sequence_text = Some Q \<Longrightarrow> unsatisfiable (embed_query Q)"
  using solver_relu_sequence_text_decodes Imported_Marabou_Native_Relu_Sequence.imported_before_relu_query_unsatisfiable by simp

text \<open>
  Bytes of tests/fixtures/marabou/solver_relu_chain.mqx
  (242 bytes, SHA-256 847461473caa5e51610596842f5a6d13d63625dd0588cc79cdd18fd7a1f4e22a).
\<close>

definition solver_relu_chain_text :: bytes where
  "solver_relu_chain_text = [109, 97, 114, 97, 98, 111, 117, 45, 101, 120, 97, 99, 116, 45, 113, 117, 101, 114, 121, 45, 118, 49, 10, 101,
    113, 32, 49, 32, 120, 48, 32, 45, 49, 32, 120, 52, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 50,
    32, 45, 49, 32, 120, 49, 32, 61, 32, 45, 49, 47, 52, 10, 101, 113, 32, 49, 32, 120, 51, 32, 45, 49,
    32, 120, 53, 32, 61, 32, 48, 10, 108, 111, 119, 101, 114, 32, 120, 48, 32, 45, 50, 10, 117, 112, 112, 101,
    114, 32, 120, 48, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 49, 32, 48, 10, 117, 112, 112, 101, 114, 32,
    120, 49, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 50, 32, 45, 50, 10, 117, 112, 112, 101, 114, 32, 120,
    50, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 51, 32, 48, 10, 117, 112, 112, 101, 114, 32, 120, 51, 32,
    50, 10, 108, 111, 119, 101, 114, 32, 120, 52, 32, 45, 50, 10, 117, 112, 112, 101, 114, 32, 120, 52, 32, 45,
    49, 47, 50, 10, 108, 111, 119, 101, 114, 32, 120, 53, 32, 49, 47, 52, 10, 117, 112, 112, 101, 114, 32, 120,
    53, 32, 50, 10, 114, 101, 108, 117, 32, 120, 48, 32, 120, 49, 10, 114, 101, 108, 117, 32, 120, 50, 32, 120,
    51, 10]"

external_file "tests/fixtures/marabou/solver_relu_chain.mqx"

ML \<open>
  Exact_Query_Text.check_file \<^theory> @{thm solver_relu_chain_text_def}
    "tests/fixtures/marabou/solver_relu_chain.mqx"
\<close>

lemma solver_relu_chain_text_decodes:
  "decode_query solver_relu_chain_text = Some Imported_Marabou_Native_Relu_Chain.imported_before_relu_query"
  by code_simp

theorem solver_relu_chain_text_unsatisfiable:
  "decode_query solver_relu_chain_text = Some Q \<Longrightarrow> unsatisfiable (embed_query Q)"
  using solver_relu_chain_text_decodes Imported_Marabou_Native_Relu_Chain.imported_before_relu_query_unsatisfiable by simp

text \<open>
  Bytes of tests/fixtures/marabou/solver_relu_sat.mqx
  (266 bytes, SHA-256 f87f12009a19f3f716d1dc1e1b16dac6ea384c997638ba8e7096a1ecee7fc770).
\<close>

definition solver_relu_sat_text :: bytes where
  "solver_relu_sat_text = [109, 97, 114, 97, 98, 111, 117, 45, 101, 120, 97, 99, 116, 45, 113, 117, 101, 114, 121, 45, 118, 49, 10, 101,
    113, 32, 49, 32, 120, 48, 32, 45, 49, 32, 120, 52, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 50,
    32, 45, 49, 32, 120, 53, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 49, 32, 49, 32, 120, 51, 32,
    45, 49, 32, 120, 54, 32, 61, 32, 48, 10, 108, 111, 119, 101, 114, 32, 120, 48, 32, 45, 50, 10, 117, 112,
    112, 101, 114, 32, 120, 48, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 49, 32, 48, 10, 117, 112, 112, 101,
    114, 32, 120, 49, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 50, 32, 45, 50, 10, 117, 112, 112, 101, 114,
    32, 120, 50, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 51, 32, 48, 10, 117, 112, 112, 101, 114, 32, 120,
    51, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 52, 32, 49, 47, 50, 10, 117, 112, 112, 101, 114, 32, 120,
    52, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 53, 32, 45, 50, 10, 117, 112, 112, 101, 114, 32, 120, 53,
    32, 45, 49, 47, 52, 10, 108, 111, 119, 101, 114, 32, 120, 54, 32, 48, 10, 117, 112, 112, 101, 114, 32, 120,
    54, 32, 49, 10, 114, 101, 108, 117, 32, 120, 48, 32, 120, 49, 10, 114, 101, 108, 117, 32, 120, 50, 32, 120,
    51, 10]"

external_file "tests/fixtures/marabou/solver_relu_sat.mqx"

ML \<open>
  Exact_Query_Text.check_file \<^theory> @{thm solver_relu_sat_text_def}
    "tests/fixtures/marabou/solver_relu_sat.mqx"
\<close>

lemma solver_relu_sat_text_decodes:
  "decode_query solver_relu_sat_text = Some Imported_Marabou_Native_Relu_Sat.imported_before_relu_query"
  by code_simp

theorem solver_relu_sat_text_model:
  "decode_query solver_relu_sat_text = Some Q \<Longrightarrow>
    satisfies_query (assignment_valuation Imported_Marabou_Native_Relu_Sat.imported_assignment) (embed_query Q)"
  using solver_relu_sat_text_decodes Imported_Marabou_Native_Relu_Sat.imported_before_relu_query_model by simp

theorem solver_relu_sat_text_satisfiable:
  "decode_query solver_relu_sat_text = Some Q \<Longrightarrow> satisfiable (embed_query Q)"
  using solver_relu_sat_text_model unfolding satisfiable_def by blast

end
