theory Imported_Marabou_Propagation_Chain
  imports "Marabou_Verification.Rational_Proof_Trees"
begin

text \<open>
  Generated by the untrusted Marabou JSON adapter. All numbers below denote
  exact rationals decoded from the serialized decimal tokens. This theorem
  concerns this explicit processed query, not an earlier neural-network input.
  Expected query SHA-256: 142321c8547aa6678e4b399fc56afe49df6fbd04ff38aeb205aade1ca90acc7f
  Certificate SHA-256: 5bd3188d803a67e0090d7fc1b721cea03c831c8abf8ead83c6c6120997b333a6
\<close>

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 2), ((-1), 3)]) 0, RatEq (RatExpr 0 [((-1), 1), (1, 4), ((-1), 5), ((-1), 6)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 (1 / 2), RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 3, RatLower 3 0, RatUpper 3 0, RatLower 4 (3 / 4), RatUpper 4 2, RatLower 5 0, RatUpper 5 3, RatLower 6 0, RatUpper 6 0],
     rat_relu_atoms = [ReLU 0 1, ReLU 1 4]\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Relu_Upper 0 1 (1 / 2) (1 / 2)
    (Relu_Upper 1 4 (1 / 2) (1 / 2)
      (Linear_Unsat [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]))"

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

end
