theory Imported_Marabou_Prepared_Inequality_Relu_Unsat
  imports "Marabou_Verification.Tableau_Auxiliary_Sequence"
    "Marabou_Verification.ReLU_Auxiliary_Sequence"
begin

text \<open>
  Generated by the untrusted source-query adapter from four captured artifacts.
  Numbers denote exact rationals decoded from serialized decimal tokens.
  The source was captured before initialization; introductions are harness
  proposals recovered from added columns, not a native transformation log.
  The proofs below check reordering, introductions, the independent processed
  query, and the recursive proof. Neither the JSON decoder nor C++ is verified.
  Source query SHA-256: 225baf6e3f290fd1d282f683780232affd6a8184e9383120c74d2be40ebfed47
  Introduction list SHA-256: 8b0d136f369b128f79fac0286d25e9fd05e1bbe9ac560c7df1b44b454d53f9aa
  Processed query SHA-256: 65c22c03ca3cb481f47caf215ea4c4bb365a56cd61aa041ed8d443658d0a2476
  Certificate SHA-256: 635938b881257dc677249346762054f9940d563ba3aea324c7844ef16fe601e9
\<close>

definition imported_source_query :: rat_query where
  "imported_source_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), (1, 2)]) (-1), RatEq (RatExpr 0 [(1, 1), (1, 3)]) 1, RatEq (RatExpr 0 [(1, 1), ((-1), 0), ((-1), 4)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 1, RatLower 3 (-1), RatUpper 3 0, RatLower 4 0, RatUpper 4 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_source_column_query :: rat_query where
  "imported_source_column_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), (1, 2)]) (-1), RatEq (RatExpr 0 [(1, 1), (1, 3)]) 1, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 4)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 1, RatLower 3 (-1), RatUpper 3 0, RatLower 4 0, RatUpper 4 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

lemma imported_source_term_order:
  "satisfies_query v (embed_query imported_source_column_query) \<longleftrightarrow>
    satisfies_query v (embed_query imported_source_query)"
  by (simp add: imported_source_query_def imported_source_column_query_def
      embed_query_def satisfies_query_def algebra_simps)

definition imported_steps :: "fixed_aux_step list" where
  "imported_steps = [(0, 5), (1, 6), (2, 7)]"

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), (1, 2), ((-1), 5)]) 0, RatEq (RatExpr 0 [(1, 1), (1, 3), ((-1), 6)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 4), ((-1), 7)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 1, RatLower 3 (-1), RatUpper 3 0, RatLower 4 0, RatUpper 4 2, RatLower 5 (-1), RatUpper 5 (-1), RatLower 6 1, RatUpper 6 1, RatLower 7 0, RatUpper 7 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Linear_Bound (RatLower 0 (-1)) [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1]
    (Relu_Aux_Upper 0 1 4 (-1) (500001 / 500000) [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
      [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
      (Linear_Bound (RatUpper 0 (-1)) [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
        (Relu_Upper 0 1 (-1) 0
          (Linear_Unsat [1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1]))))"

lemma imported_steps_match_query:
  "rat_introduce_fixed_aux_sequence imported_source_column_query imported_steps =
    Some imported_query"
  by code_simp

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

lemma imported_source_certificate_checked:
  "check_after_fixed_aux_sequence imported_source_column_query
    imported_steps imported_certificate"
  by (simp add: check_after_fixed_aux_sequence_def imported_steps_match_query
      imported_certificate_checked)

theorem imported_source_equisatisfiable:
  "satisfiable (embed_query imported_query) \<longleftrightarrow>
    satisfiable (embed_query imported_source_query)"
  using fixed_aux_sequence_satisfiable_iff[OF imported_steps_match_query]
  by (simp add: satisfiable_def imported_source_term_order)

theorem imported_source_query_unsatisfiable:
  "unsatisfiable (embed_query imported_source_query)"
proof -
  have "unsatisfiable (embed_query imported_source_column_query)"
    by (rule check_after_fixed_aux_sequence_sound[OF imported_source_certificate_checked])
  then show ?thesis
    by (simp add: unsatisfiable_def satisfiable_def imported_source_term_order)
qed

text \<open>
  Additional native ReLU introduction sequence and independent before-query.
  Each step checks the current query. The whole final result must equal
  imported_source_query, captured independently after the native calls.
  Before-ReLU query SHA-256: 6680156ad676fa901248c9ba3b122833e0a5fe17113e6141858addea60f059f3
  ReLU introduction sequence SHA-256: 5b031167fb157d4ded8bab447da1178a8e437ad4aefb8611cd6923590fa962e2
\<close>

definition imported_before_relu_query :: rat_query where
  "imported_before_relu_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), (1, 2)]) (-1), RatEq (RatExpr 0 [(1, 1), (1, 3)]) 1],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 0, RatUpper 1 2, RatLower 2 0, RatUpper 2 1, RatLower 3 (-1), RatUpper 3 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_relu_steps :: "relu_aux_step list" where
  "imported_relu_steps = [ReLU_Aux_Step 0 1 4 (Some (-2))]"

lemma imported_relu_introductions_match_source:
  "rat_introduce_relu_aux_sequence imported_before_relu_query imported_relu_steps =
    Some imported_source_query"
  by code_simp

theorem imported_relu_introductions_equisatisfiable:
  "satisfiable (embed_query imported_source_query) \<longleftrightarrow>
    satisfiable (embed_query imported_before_relu_query)"
  by (rule relu_aux_sequence_satisfiable_iff[OF imported_relu_introductions_match_source])

theorem imported_before_relu_processed_equisatisfiable:
  "satisfiable (embed_query imported_query) \<longleftrightarrow>
    satisfiable (embed_query imported_before_relu_query)"
  using imported_source_equisatisfiable imported_relu_introductions_equisatisfiable by blast

lemma imported_before_relu_certificate_checked:
  "check_after_relu_aux_sequence imported_before_relu_query imported_relu_steps
    imported_steps imported_certificate"
  by code_simp

theorem imported_before_relu_query_unsatisfiable:
  "unsatisfiable (embed_query imported_before_relu_query)"
  by (rule check_after_relu_aux_sequence_sound[OF imported_before_relu_certificate_checked])

end
