theory Imported_Marabou_Explained_Positive
  imports "Marabou_Verification.Rational_Proof_Trees"
begin

text \<open>
  Generated by the untrusted Marabou JSON adapter. All numbers below denote
  exact rationals decoded from the serialized decimal tokens. This theorem
  concerns this explicit processed query, not an earlier neural-network input.
  Expected query SHA-256: 81480b03e9628bb02871172a9457976d3915762faf044d74d60a0d6d010a0852
  Certificate SHA-256: 630ea9f82dc0b08cb4209f6cf4b30b5dc64d269e5151a9530fda70b6535485d0
\<close>

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 2), ((-1), 5)]) 0, RatEq (RatExpr 0 [(1, 0), ((-2), 3), (1, 4), ((-1), 6)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 2, RatLower 1 (3 / 4), RatUpper 1 2, RatLower 2 0, RatUpper 2 4, RatLower 3 (-1), RatUpper 3 (1 / 2), RatLower 4 (1 / 2), RatUpper 4 2, RatLower 5 0, RatUpper 5 0, RatLower 6 0, RatUpper 6 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Linear_Bound (RatUpper 0 (1 / 2)) [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1]
    (Relu_Upper 0 1 (1 / 2) (1 / 2)
      (Linear_Unsat [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))"

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

end
