theory Imported_Marabou_Example_Relu_Chain_Unsat
  imports "Marabou_Verification.Exact_Query_Format" Imported_Marabou_Native_Relu_Chain
begin

text \<open>
  Generated by the untrusted query-file adapter. The theorems below concern
  decode_query of the exact bytes of examples/relu_chain_unsat.mqx
  (244 bytes, SHA-256 99f6c7864570c53bbd91751cb6676dc34e21a30b371ca5280b58b9cdfae12e31), which the build checks against the file.
  The native solver read this file with an untrusted C++ reader. Isabelle
  proves that the file's decoding has exactly the constraints of the query
  captured from that run, so neither the reader, the solver nor the JSON
  import is trusted for these conclusions.
\<close>

definition query_file :: bytes where
  "query_file = [109, 97, 114, 97, 98, 111, 117, 45, 101, 120, 97, 99, 116, 45, 113, 117, 101, 114, 121, 45, 118, 49, 10, 114,
    101, 108, 117, 32, 120, 48, 32, 120, 49, 10, 114, 101, 108, 117, 32, 120, 50, 32, 120, 51, 10, 101, 113, 32,
    49, 32, 120, 48, 32, 45, 49, 32, 120, 52, 32, 61, 32, 48, 10, 101, 113, 32, 49, 32, 120, 50, 32, 45,
    49, 32, 120, 49, 32, 61, 32, 45, 48, 46, 50, 53, 10, 101, 113, 32, 49, 32, 120, 51, 32, 45, 49, 32,
    120, 53, 32, 61, 32, 48, 10, 108, 111, 119, 101, 114, 32, 120, 52, 32, 45, 50, 10, 117, 112, 112, 101, 114,
    32, 120, 52, 32, 45, 48, 46, 53, 10, 108, 111, 119, 101, 114, 32, 120, 53, 32, 48, 46, 50, 53, 10, 117,
    112, 112, 101, 114, 32, 120, 53, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 48, 32, 45, 50, 10, 117, 112,
    112, 101, 114, 32, 120, 48, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 49, 32, 48, 10, 117, 112, 112, 101,
    114, 32, 120, 49, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 50, 32, 45, 50, 10, 117, 112, 112, 101, 114,
    32, 120, 50, 32, 50, 10, 108, 111, 119, 101, 114, 32, 120, 51, 32, 48, 10, 117, 112, 112, 101, 114, 32, 120,
    51, 32, 50, 10]"

external_file "examples/relu_chain_unsat.mqx"

ML \<open>
  Exact_Query_Text.check_file \<^theory> @{thm query_file_def} "examples/relu_chain_unsat.mqx"
\<close>

lemma query_file_decodes_like_capture:
  "decodes_like query_file Imported_Marabou_Native_Relu_Chain.imported_before_relu_query"
  by code_simp

theorem query_file_decodes:
  "\<exists>Q. decode_query query_file = Some Q"
  by (rule decodes_like_decodes[OF query_file_decodes_like_capture])

theorem query_file_unsatisfiable:
  "decode_query query_file = Some Q \<Longrightarrow> unsatisfiable (embed_query Q)"
  by (rule decodes_like_unsatisfiable[OF query_file_decodes_like_capture
        Imported_Marabou_Native_Relu_Chain.imported_before_relu_query_unsatisfiable])

end
