theory Imported_Marabou_Nested
  imports "Marabou_Verification.Rational_Proof_Trees"
begin

text \<open>
  Generated by the untrusted Marabou JSON adapter. All numbers below denote
  exact rationals decoded from the serialized decimal tokens. This theorem
  concerns this explicit processed query, not an earlier neural-network input.
  Expected query SHA-256: adb4e6045b1b8e7c2f95d17e67b857d61e0b53d983592b3f72e21307e4e0d919
  Certificate SHA-256: 4cfe09cf690c83dd3aaf4ac8ca6fc0ceb8a7d21e35eed0470f06d10fd83dadec
\<close>

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 2), ((-1), 3)]) 0, RatEq (RatExpr 0 [((-1), 4), (1, 5), ((-1), 6), ((-1), 7)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 0, RatLower 1 1, RatUpper 1 2, RatLower 2 0, RatUpper 2 3, RatLower 3 0, RatUpper 3 0, RatLower 4 (-1), RatUpper 4 1, RatLower 5 0, RatUpper 5 1, RatLower 6 0, RatUpper 6 2, RatLower 7 0, RatUpper 7 0],
     rat_relu_atoms = [ReLU 0 1, ReLU 4 5]\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Relu_Split 4 5
    (Relu_Split 0 1
      (Linear_Unsat [1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0])
      (Linear_Unsat [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))
    (Relu_Split 0 1
      (Linear_Unsat [1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0])
      (Linear_Unsat [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))"

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

end
