theory Imported_Marabou_Solver_Relu_Split
  imports "Marabou_Verification.Rational_Proof_Trees"
begin

text \<open>
  Generated by the untrusted Marabou JSON adapter. All numbers below denote
  exact rationals decoded from the serialized decimal tokens. This theorem
  concerns this explicit processed query, not an earlier neural-network input.
  Expected query SHA-256: df27a42e43fb65767777bef0387d056e340afbce25f371f75e516153d7b1cfcb
  Certificate SHA-256: 0d5c334f385d725ea28430bb756dc3546ccd4b50459d7bb5cb562fc7d6ecac19
\<close>

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 1), ((-1), 3), ((-1), 5), ((-1), 9)]) 0, RatEq (RatExpr 0 [(1, 1), (1, 3), ((-1), 6), ((-1), 10)]) 0, RatEq (RatExpr 0 [(1, 2), ((-1), 4), ((-1), 7), ((-1), 11)]) 0, RatEq (RatExpr 0 [(1, 2), (1, 4), ((-1), 8), ((-1), 12)]) 0, RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 2), ((-1), 13)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 1, RatLower 1 0, RatUpper 1 1, RatLower 2 0, RatUpper 2 1, RatLower 3 (-1), RatUpper 3 1, RatLower 4 (-1), RatUpper 4 1, RatLower 5 0, RatUpper 5 2, RatLower 6 0, RatUpper 6 2, RatLower 7 0, RatUpper 7 2, RatLower 8 0, RatUpper 8 2, RatLower 9 (1 / 4), RatUpper 9 (1 / 4), RatLower 10 (1 / 4), RatUpper 10 (1 / 4), RatLower 11 (1 / 4), RatUpper 11 (1 / 4), RatLower 12 (1 / 4), RatUpper 12 (1 / 4), RatLower 13 0, RatUpper 13 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Relu_Split 0 1
    (Linear_Unsat [2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0])
    (Linear_Unsat [2, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0])"

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

end
