theory Imported_Marabou_Example_Preprocess_Inequality_Unsat
  imports "Marabou_Verification.Exact_Query_Format" Imported_Marabou_Preprocessed_Inequality_Unsat
begin

text \<open>
  Generated by the untrusted query-file adapter. The theorems below concern
  decode_query of the exact bytes of examples/preprocess_inequality_unsat.mqx
  (106 bytes, SHA-256 7861f3015219edf9f6c2f85a6e49cb7a36c87245bc0f6b8c1e3f58b095d7be12), which the build checks against the file.
  The native solver read this file and ran Marabou's own preprocessing.
  The replay theory checks the native slack and ReLU introductions, exact
  re-derivations of the tightened bounds, and a projection onto the captured
  preprocessed query (or onto derived crossing bounds). Neither the reader,
  the solver, the preprocessing record nor the JSON import is trusted.
\<close>

definition query_file :: bytes where
  "query_file = [109, 97, 114, 97, 98, 111, 117, 45, 101, 120, 97, 99, 116, 45, 113, 117, 101, 114, 121, 45, 118, 49, 10, 103,
    101, 32, 49, 32, 120, 48, 32, 49, 32, 120, 49, 32, 62, 61, 32, 51, 10, 108, 101, 32, 49, 32, 120, 50,
    32, 45, 49, 32, 120, 49, 32, 60, 61, 32, 45, 49, 10, 108, 111, 119, 101, 114, 32, 120, 48, 32, 45, 49,
    10, 117, 112, 112, 101, 114, 32, 120, 48, 32, 49, 10, 117, 112, 112, 101, 114, 32, 120, 49, 32, 51, 10, 114,
    101, 108, 117, 32, 120, 49, 32, 120, 50, 10]"

external_file "examples/preprocess_inequality_unsat.mqx"

ML \<open>
  Exact_Query_Text.check_file \<^theory> @{thm query_file_def} "examples/preprocess_inequality_unsat.mqx"
\<close>

lemma query_file_decodes_like_capture:
  "decodes_like query_file Imported_Marabou_Preprocessed_Inequality_Unsat.imported_file_query"
  by code_simp

theorem query_file_decodes:
  "\<exists>Q. decode_query query_file = Some Q"
  by (rule decodes_like_decodes[OF query_file_decodes_like_capture])

theorem query_file_unsatisfiable:
  "decode_query query_file = Some Q \<Longrightarrow> unsatisfiable (embed_query Q)"
  by (rule decodes_like_unsatisfiable[OF query_file_decodes_like_capture
        Imported_Marabou_Preprocessed_Inequality_Unsat.imported_file_query_unsatisfiable])

end
