theory Imported_Marabou_Solver_Linear
  imports "Marabou_Verification.Rational_Proof_Trees"
begin

text \<open>
  Generated by the untrusted Marabou JSON adapter. All numbers below denote
  exact rationals decoded from the serialized decimal tokens. This theorem
  concerns this explicit processed query, not an earlier neural-network input.
  Expected query SHA-256: 5a97073889b9bb367985445742cda4977aef81ff08c592407383e02635612768
  Certificate SHA-256: 37f5a61c79370f5778cefba7b5fa24953747b18d71f204e506a05f6cc9869343
\<close>

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 1), ((-1), 2)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 (1 / 4), RatLower 1 (1 / 2), RatUpper 1 2, RatLower 2 0, RatUpper 2 0],
     rat_relu_atoms = []\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Linear_Unsat [0, 1, 0, 1, 1, 0, 1, 0]"

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

end
