theory Imported_Marabou_Propagation
  imports "Marabou_Verification.Rational_Proof_Trees"
begin

text \<open>
  Generated by the untrusted Marabou JSON adapter. All numbers below denote
  exact rationals decoded from the serialized decimal tokens. This theorem
  concerns this explicit processed query, not an earlier neural-network input.
  Expected query SHA-256: e080f96600d33ffe31f3ca2f50cb4149bb7988352871a7a01f7af1b28eb10539
  Certificate SHA-256: 8c834c250e48ed5ab41228d70620816868a9820ac0708f6bbac8ccb90d85cc15
\<close>

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 2), ((-1), 3)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 (-1 / 2), RatLower 1 (1 / 4), RatUpper 1 2, RatLower 2 0, RatUpper 2 3, RatLower 3 0, RatUpper 3 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Relu_Upper 0 1 (-1 / 2) 0
    (Linear_Unsat [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0])"

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

end
