theory Imported_Marabou_Preprocessed_Mixed_Sat
  imports "Marabou_Verification.Rational_Assignment"
begin

text \<open>
  Generated by the untrusted preprocessing adapter. The native run used
  Marabou's preprocessing; Engine::extractSolution mapped its solution back
  to the file's variables. The code_simp proof checks every atom exactly.
  Assignment SHA-256: 99c2fe2a756d6f4dd137c1bd96be75b3624f1a70af08299f7a29721341222a61
\<close>

definition imported_file_query :: rat_query where
  "imported_file_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 3)]) 0, RatLe (RatExpr 0 [(1, 1), (1, 2)]) (3 / 2), RatGe (RatExpr 0 [(1, 3)]) (1 / 2)],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 2, RatLower 2 (1 / 4), RatUpper 2 (1 / 4), RatUpper 3 2],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_assignment :: rat_assignment where
  "imported_assignment = [(0, (1 / 2)), (1, (1 / 2)), (2, (1 / 4)), (3, (1 / 2))]"

lemma imported_file_assignment_checked:
  "check_rat_assignment imported_file_query imported_assignment"
  by code_simp

theorem imported_file_query_model:
  "satisfies_query (assignment_valuation imported_assignment) (embed_query imported_file_query)"
  by (rule check_rat_assignment_sound[OF imported_file_assignment_checked])

end
