theory Imported_Marabou_Linear
  imports "Marabou_Verification.Rational_Proof_Trees"
begin

text \<open>
  Generated by the untrusted Marabou JSON adapter. All numbers below denote
  exact rationals decoded from the serialized decimal tokens. This theorem
  concerns this explicit processed query, not an earlier neural-network input.
  Expected query SHA-256: e6a661d7290d57cac01fcc72f16e37677c10a2b1acc448a6a0eef6019f5a1990
  Certificate SHA-256: cf63076dcaaa8770166c7b7e1385ca5113f2e7c0a4115860806dced9cab5950e
\<close>

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [(1, 0), ((-1), 1)]) 0],
     rat_query_bounds = [RatLower 0 (-2), RatUpper 0 (1 / 4), RatLower 1 (1 / 2), RatUpper 1 2],
     rat_relu_atoms = []\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Linear_Unsat [0, (1 / 2), 0, (1 / 2), (1 / 2), 0]"

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

end
