theory Imported_Marabou_Propagation_Positive
  imports "Marabou_Verification.Rational_Proof_Trees"
begin

text \<open>
  Generated by the untrusted Marabou JSON adapter. All numbers below denote
  exact rationals decoded from the serialized decimal tokens. This theorem
  concerns this explicit processed query, not an earlier neural-network input.
  Expected query SHA-256: 05d45c2ed0e44e09af0192fdf5cb4d764dc79c2473aa5b644cf9f0199f1e95d3
  Certificate SHA-256: 34cec27e90b900e33c8d850a59017d66fc43c5b562dbf5a0e8a9eaa783ca4681
\<close>

definition imported_query :: rat_query where
  "imported_query = \<lparr>rat_linear_atoms = [RatEq (RatExpr 0 [((-1), 0), (1, 1), ((-1), 2), ((-1), 3)]) 0],
     rat_query_bounds = [RatLower 0 (-1), RatUpper 0 (1 / 2), RatLower 1 (3 / 4), RatUpper 1 2, RatLower 2 0, RatUpper 2 3, RatLower 3 0, RatUpper 3 0],
     rat_relu_atoms = [ReLU 0 1]\<rparr>"

definition imported_certificate :: certificate where
  "imported_certificate = Relu_Upper 0 1 (1 / 2) (1 / 2)
    (Linear_Unsat [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0])"

lemma imported_certificate_checked:
  "check_certificate imported_query imported_certificate"
  by code_simp

theorem imported_query_unsatisfiable:
  "unsatisfiable (embed_query imported_query)"
  by (rule check_certificate_sound[OF imported_certificate_checked])

end
